const cardDatabase = [

  { name: "Abomination", image: "Abomination.jpg" },
  { name: "Absorbing Man", image: "Absorbing Man.jpg" },
  { name: "Adam Warlock", image: "Adam Warlock.jpg" },
  { name: "Adamantium Infusion", image: "Adamantium Infusion.jpg" },
  { name: "Agamotto", image: "Agamotto.jpg" },
  { name: "Agatha Harkness", image: "Agatha Harkness.jpg" },
  { name: "Agony", image: "Agony.jpg" },
  { name: "Air-Walker", image: "Air-Walker.jpg" },
  { name: "Aero", image: "Aero.jpg" },
  { name: "Ajax", image: "Ajax.jpg" },
  { name: "Agent 13", image: "Agent 13.jpg" },
  { name: "Agent Coulson", image: "Agent Coulson.jpg" },
  { name: "Agent Venom", image: "Agent Venom.jpg" },
  { name: "America Chavez", image: "America Chavez.jpg" },
  { name: "Ancient One", image: "Ancient One.jpg" },
  { name: "Angel", image: "Angel.jpg" },
  { name: "Angela", image: "Angela.jpg" },
  { name: "Annihilus", image: "Annihilus.jpg" },
  { name: "Ant-Man", image: "Ant-Man.jpg" },
  { name: "Anti-Venom", image: "Anti-Venom.jpg" },
  { name: "Apocalypse", image: "Apocalypse.jpg" },
  { name: "Alioth", image: "Alioth.jpg" },
  { name: "Araña", image: "Arana.jpg" },
  { name: "Arishem", image: "Arishem.jpg" },
  { name: "Arnim Zola", image: "Arnim Zola.jpg" },
  { name: "Armor", image: "Armor.jpg" },
  { name: "Ares", image: "Ares.jpg" },
  { name: "Astral Projection", image: "Astral Projection.jpg" },
  { name: "Attuma", image: "Attuma.jpg" },
  { name: "Aurora", image: "Aurora.jpg" },
  { name: "Awesome Andy", image: "Awesome Andy.jpg" },
  { name: "Baron Mordo", image: "Baron Mordo.jpg" },
  { name: "Baron Zemo", image: "Baron Zemo.jpg" },
  { name: "Bast", image: "Bast.jpg" },
  { name: "Bastion", image: "Bastion.jpg" },
  { name: "Batroc the Leaper", image: "Batroc the Leaper.jpg" },
  { name: "Beta Ray Bill", image: "Beta Ray Bill.jpg" },
  { name: "Bishop", image: "Bishop.jpg" },
  { name: "Black Bolt", image: "Black Bolt.jpg" },
  { name: "Black Cat", image: "Black Cat.jpg" },
  { name: "Black Knight", image: "Black Knight.jpg" },
  { name: "Black Panther", image: "Black Panther.jpg" },
  { name: "Black Swann", image: "Black Swann.jpg" },
  { name: "Black Widow", image: "Black Widow.jpg" },
  { name: "Blade", image: "Blade.jpg" },
  { name: "Blink", image: "Blink.jpg" },
  { name: "Blob", image: "Blob.jpg" },
  { name: "Blue Marvel", image: "Blue Marvel.jpg" },
  { name: "Brood", image: "Brood.jpg" },
  { name: "Bruce Banner", image: "Bruce Banner.jpg" },
  { name: "Bucky Barnes", image: "Bucky Barnes.jpg" },
  { name: "Bullseye", image: "Bullseye.jpg" },
  { name: "Cable", image: "Cable.jpg" },
  { name: "Caiera", image: "Caiera.jpg" },
  { name: "Cannonball", image: "Cannonball.jpg" },
  { name: "Captain America", image: "Captain America.jpg" },
  { name: "Captain Carter", image: "Captain Carter.jpg" },
  { name: "Captain Marvel", image: "Captain Marvel.jpg" },
  { name: "Carnage", image: "Carnage.jpg" },
  { name: "Cassandra Nova", image: "Cassandra Nova.jpg" },
  { name: "Cerebro", image: "Cerebro.jpg" },
  { name: "Chamber", image: "Chamber.jpg" },
  { name: "Chameleon", image: "Chameleon.jpg" },
  { name: "Clea", image: "Clea.jpg" },
  { name: "Cloak", image: "Cloak.jpg" },
  { name: "Cobra", image: "Cobra.jpg" },
  { name: "Colleen Wing", image: "Colleen Wing.jpg" },
  { name: "Colonel America", image: "Colonel America.jpg" },
  { name: "Colossus", image: "Colossus.jpg" },
  { name: "Copycat", image: "Copycat.jpg" },
  { name: "Corvus Glaive", image: "Corvus Glaive.jpg" },
  { name: "Cosmic Ghost Rider", image: "Cosmic Ghost Rider.jpg" },
  { name: "Cosmo", image: "Cosmo.jpg" },
  { name: "Crossbones", image: "Crossbones.jpg" },
  { name: "Crystal", image: "Crystal.jpg" },
  { name: "Cull Obsidian", image: "Cull Obsidian.jpg" },
  { name: "Cyclops", image: "Cyclops.jpg" },
  { name: "Dagger", image: "Dagger.jpg" },
  { name: "Daken", image: "Daken.jpg" },
  { name: "Danger", image: "Danger.jpg" },
  { name: "Daredevil", image: "Daredevil.jpg" },
  { name: "Darkhawk", image: "Darkhawk.jpg" },
  { name: "Dazzler", image: "Dazzler.jpg" },
  { name: "Deadpool", image: "Deadpool.jpg" },
  { name: "Deafening Chord", image: "Deafening Chord.jpg" },
  { name: "Death", image: "Death.jpg" },
  { name: "Deathlok", image: "Deathlok.jpg" },
  { name: "Debrii", image: "Debrii.jpg" },
  { name: "Destroyer", image: "Destroyer.jpg" },
  { name: "Devil Dinosaur", image: "Devil Dinosaur.jpg" },
  { name: "Diamondback", image: "Diamondback.jpg" },
  { name: "Doctor Doom", image: "Doctor Doom.jpg" },
  { name: "Doctor Doom 2099", image: "Doctor Doom 2099.jpg" },
  { name: "Doctor Octopus", image: "Doctor Octopus.jpg" },
  { name: "Doctor Strange", image: "Doctor Strange.jpg" },
  { name: "Domino", image: "Domino.jpg" },
  { name: "Dormammu", image: "Dormammu.jpg" },
  { name: "Dracula", image: "Dracula.jpg" },
  { name: "Dragon Lord", image: "Dragon Lord.jpg" },
  { name: "Dragon of the Moon", image: "Dragon of the Moon.jpg" },
  { name: "Drax", image: "Drax.jpg" },
  { name: "Drax Avatar of Life", image: "Drax Avatar of Life.jpg" },
  { name: "Ebony Maw", image: "Ebony Maw.jpg" },
  { name: "Echo", image: "Echo.jpg" },
  { name: "Electro", image: "Electro.jpg" },
  { name: "Elektra", image: "Elektra.jpg" },
  { name: "Elixir", image: "Elixir.jpg" },
  { name: "Elsa Bloodstone", image: "Elsa Bloodstone.jpg" },
  { name: "Emperor Hulkling", image: "Emperor Hulkling.jpg" },
  { name: "Enchantress", image: "Enchantress.jpg" },
  { name: "Esme Cuckoo", image: "Esme Cuckoo.jpg" },
  { name: "Eson", image: "Eson.jpg" },
  { name: "Ezekiel Sims", image: "Ezekiel Sims.jpg" },
  { name: "Falcon", image: "Falcon.jpg" },
  { name: "Fan Fei", image: "Fan Fei.jpg" },
  { name: "Fantasticar", image: "Fantasticar.jpg" },
  { name: "Fantomex", image: "Fantomex.jpg" },
  { name: "Fastball Special", image: "Fastball Special.jpg" },
  { name: "Fenris Wolf", image: "Fenris Wolf.jpg" },
  { name: "Fin Fang Foom", image: "Fin Fang Foom.jpg" },
  { name: "Firehair", image: "Firehair.jpg" },
  { name: "Firelord", image: "Firelord.jpg" },
  { name: "Forge", image: "Forge.jpg" },
  { name: "Frigga", image: "Frigga.jpg" },
  { name: "Galacta", image: "Galacta.jpg" },
  { name: "Galactus", image: "Galactus.jpg" },
  { name: "Galactus First Steps", image: "Galactus First Steps.jpg" },
  { name: "Gambit", image: "Gambit.jpg" },
  { name: "Gamora", image: "Gamora.jpg" },
  { name: "Ghost", image: "Ghost.jpg" },
  { name: "Ghost Rider", image: "Ghost Rider.jpg" },
  { name: "Ghost-Spider", image: "Ghost-Spider.jpg" },
  { name: "Giganto", image: "Giganto.jpg" },
  { name: "Gilgamesh", image: "Gilgamesh.jpg" },
  { name: "Gladiator", image: "Gladiator.jpg" },
  { name: "Goliath", image: "Goliath.jpg" },
  { name: "Goose", image: "Goose.jpg" },
  { name: "Gorgon", image: "Gorgon.jpg" },
  { name: "Gorr", image: "Gorr.jpg" },
  { name: "Grand Master", image: "Grand Master.jpg" },
  { name: "Green Goblin", image: "Green Goblin.jpg" },
  { name: "Groot", image: "Groot.jpg" },
  { name: "Gwenpool", image: "Gwenpool.jpg" },
  { name: "H.E.R.B.I.E.", image: "H.E.R.B.I.E..jpg" },
  { name: "Havok", image: "Havok.jpg" },
  { name: "Hawkeye Kate Bishop", image: "Hawkeye Kate Bishop.jpg" },
  { name: "Hazmat", image: "Hazmat.jpg" },
  { name: "Headpool", image: "Headpool.jpg" },
  { name: "Heimdall", image: "Heimdall.jpg" },
  { name: "Hela", image: "Hela.jpg" },
  { name: "Helicarrier", image: "Helicarrier.jpg" },
  { name: "Hellcow", image: "Hellcow.jpg" },
  { name: "Hellion", image: "Hellion.jpg" },
  { name: "High Evolutionary", image: "High Evolutionary.jpg" },
  { name: "Hit-Monkey", image: "Hit-Monkey.jpg" },
  { name: "Hobgoblin", image: "Hobgoblin.jpg" },
  { name: "Hope Summers", image: "Hope Summers.jpg" },
  { name: "Howard the Duck", image: "Howard the Duck.jpg" },
  { name: "Hulk", image: "Hulk.jpg" },
  { name: "Hulkbuster", image: "Hulkbuster.jpg" },
  { name: "Human Torch", image: "Human Torch.jpg" },
  { name: "Human Torch First Steps", image: "Human Torch First Steps.jpg" },
  { name: "Hydra Bob", image: "Hydra Bob.jpg" },
  { name: "Hydra Stomper", image: "Hydra Stomper.jpg" },
  { name: "Hydro-Man", image: "Hydro-Man.jpg" },
  { name: "Iceman", image: "Iceman.jpg" },
  { name: "Infinity Ultron", image: "Infinity Ultron.jpg" },
  { name: "Invisible Woman", image: "Invisible Woman.jpg" },
  { name: "Invisible Woman First Steps", image: "Invisible Woman First Steps.jpg" },
  { name: "Iron Fist", image: "Iron Fist.jpg" },
  { name: "Iron Lad", image: "Iron Lad.jpg" },
  { name: "Iron Man", image: "Iron Man.jpg" },
  { name: "Iron Patriot", image: "Iron Patriot.jpg" },
  { name: "Ironheart", image: "Ironheart.jpg" },
  { name: "Jane Foster", image: "Jane Foster.jpg" },
  { name: "Jean Grey", image: "Jean Grey.jpg" },
  { name: "Jeff the Baby Land Shark", image: "Jeff the Baby Land Shark.jpg" },
  { name: "Jennifer Kale", image: "Jennifer Kale.jpg" },
  { name: "Jessica Jones", image: "Jessica Jones.jpg" },
  { name: "Jim Hammond Human Torch", image: "Jim Hammond Human Torch.jpg" },
  { name: "Joaquin Torres Falcon II", image: "Joaquin Torres Falcon II.jpg" },
  { name: "Jocasta", image: "Jocasta.jpg" },
  { name: "Jubilee", image: "Jubilee.jpg" },
  { name: "Juggernaut", image: "Juggernaut.jpg" },
  { name: "Ka-Zar", image: "Ka-Zar.jpg" },
  { name: "Kahhori", image: "Kahhori.jpg" },
  { name: "Kang", image: "Kang.jpg" },
  { name: "Khonshu", image: "Khonshu.jpg" },
  { name: "Kid Omega", image: "Kid Omega.jpg" },
  { name: "Killmonger", image: "Killmonger.jpg" },
  { name: "King Eitri", image: "King Eitri.jpg" },
  { name: "Kingpin", image: "Kingpin.jpg" },
  { name: "Kitty Pryde", image: "Kitty Pryde.jpg" },
  { name: "Klaw", image: "Klaw.jpg" },
  { name: "Knull", image: "Knull.jpg" },
  { name: "Korg", image: "Korg.jpg" },
  { name: "Kraglin", image: "Kraglin.jpg" },
  { name: "Kraven", image: "Kraven.jpg" },
  { name: "Lady Deathstrike", image: "Lady Deathstrike.jpg" },
  { name: "Lady Sif", image: "Lady Sif.jpg" },
  { name: "Lasher", image: "Lasher.jpg" },
  { name: "Laufey", image: "Laufey.jpg" },
  { name: "Leader", image: "Leader.jpg" },
  { name: "Leech", image: "Leech.jpg" },
  { name: "Legion", image: "Legion.jpg" },
  { name: "Lin Lie Iron Fist", image: "Lin Lie Iron Fist.jpg" },
  { name: "Lizard", image: "Lizard.jpg" },
  { name: "Lockheed", image: "Lockheed.jpg" },
  { name: "Lockjaw", image: "Lockjaw.jpg" },
  { name: "Loki", image: "Loki.jpg" },
  { name: "Luke Cage", image: "Luke Cage.jpg" },
  { name: "Luna Snow", image: "Luna Snow.jpg" },
  { name: "M'Baku", image: "MBaku.jpg" },
  { name: "M.O.D.O.K.", image: "M.O.D.O.K..jpg" },
  { name: "Mad Thinker", image: "Mad Thinker.jpg" },
  { name: "Madame Web", image: "Madame Web.jpg" },
  { name: "Magik", image: "Magik.jpg" },
  { name: "Magneto", image: "Magneto.jpg" },
  { name: "Magus", image: "Magus.jpg" },
  { name: "Majestic Wingbeat", image: "Majestic Wingbeat.jpg" },
  { name: "Major Victory", image: "Major Victory.jpg" },
  { name: "Makkari", image: "Makkari.jpg" },
  { name: "Malekith", image: "Malekith.jpg" },
  { name: "Man-Spider", image: "Man-Spider.jpg" },
  { name: "Man-Thing", image: "Man-Thing.jpg" },
  { name: "Mantis", image: "Mantis.jpg" },
  { name: "Maria Hill", image: "Maria Hill.jpg" },
  { name: "Marrow", image: "Marrow.jpg" },
  { name: "Martyr", image: "Martyr.jpg" },
  { name: "Marvel Boy", image: "Marvel Boy.jpg" },
  { name: "Master Mold", image: "Master Mold.jpg" },
  { name: "Maverick", image: "Maverick.jpg" },
  { name: "Maximus", image: "Maximus.jpg" },
  { name: "Medusa", image: "Medusa.jpg" },
  { name: "Mercury", image: "Mercury.jpg" },
  { name: "Merlin", image: "Merlin.jpg" },
  { name: "Miek", image: "Miek.jpg" },
  { name: "Miles Morales Spider-Man", image: "Miles Morales Spider-Man.jpg" },
  { name: "Mirage", image: "Mirage.jpg" },
  { name: "Misery", image: "Misery.jpg" },
  { name: "Mister Fantastic", image: "Mister Fantastic.jpg" },
  { name: "Mister Fantastic First Steps", image: "Mister Fantastic First Steps.jpg" },
  { name: "Mister Negative", image: "Mister Negative.jpg" },
  { name: "Mister Sinister", image: "Mister Sinister.jpg" },
  { name: "Misty Knight", image: "Misty Knight.jpg" },
  { name: "Mobius M. Mobius", image: "Mobius M. Mobius.jpg" },
  { name: "Mockingbird", image: "Mockingbird.jpg" },
  { name: "Moira X", image: "Moira X.jpg" },
  { name: "Mojo", image: "Mojo.jpg" },
  { name: "Mole Man", image: "Mole Man.jpg" },
  { name: "Moon Girl", image: "Moon Girl.jpg" },
  { name: "Moon Knight", image: "Moon Knight.jpg" },
  { name: "Moondragon", image: "Moondragon.jpg" },
  { name: "Moonstone", image: "Moonstone.jpg" },
  { name: "Morbius", image: "Morbius.jpg" },
  { name: "Morgan le Fay", image: "Morgan le Fay.jpg" },
  { name: "Morph", image: "Morph.jpg" },
  { name: "Ms. Marvel", image: "Ms. Marvel.jpg" },
  { name: "Multiple Man", image: "Multiple Man.jpg" },
  { name: "Mysterio", image: "Mysterio.jpg" },
  { name: "Mystique", image: "Mystique.jpg" },
  { name: "Nakia", image: "Nakia.jpg" },
  { name: "Namor", image: "Namor.jpg" },
  { name: "Namora", image: "Namora.jpg" },
  { name: "Nebula", image: "Nebula.jpg" },
  { name: "Negasonic Teenage Warhead", image: "Negasonic Teenage Warhead.jpg" },
  { name: "Nicholas Scratch", image: "Nicholas Scratch.jpg" },
  { name: "Nick Fury", image: "Nick Fury.jpg" },
  { name: "Nico Minoru", image: "Nico Minoru.jpg" },
  { name: "Nightcrawler", image: "Nightcrawler.jpg" },
  { name: "Nightmare", image: "Nightmare.jpg" },
  { name: "Nimrod", image: "Nimrod.jpg" },
  { name: "Nocturne", image: "Nocturne.jpg" },
  { name: "Nova", image: "Nova.jpg" },
  { name: "Nova Frankie Raye", image: "Nova Frankie Raye.jpg" },
  { name: "Odin", image: "Odin.jpg" },
  { name: "Okoye", image: "Okoye.jpg" },
  { name: "Omega Red", image: "Omega Red.jpg" },
  { name: "Omega Sentinel", image: "Omega Sentinel.jpg" },
  { name: "Onslaught", image: "Onslaught.jpg" },
  { name: "Orka", image: "Orka.jpg" },
  { name: "Patriot", image: "Patriot.jpg" },
  { name: "Peni Parker", image: "Peni Parker.jpg" },
  { name: "Phastos", image: "Phastos.jpg" },
  { name: "Phoenix Force", image: "Phoenix Force.jpg" },
  { name: "Pixie", image: "Pixie.jpg" },
  { name: "Polaris", image: "Polaris.jpg" },
  { name: "Prodigy", image: "Prodigy.jpg" },
  { name: "Professor X", image: "Professor X.jpg" },
  { name: "Prowler", image: "Prowler.jpg" },
  { name: "Proxima Midnight", image: "Proxima Midnight.jpg" },
  { name: "Psylocke", image: "Psylocke.jpg" },
  { name: "Punisher", image: "Punisher.jpg" },
  { name: "Quake", image: "Quake.jpg" },
  { name: "Quicksilver", image: "Quicksilver.jpg" },
  { name: "Quinjet", image: "Quinjet.jpg" },
  { name: "Ravonna Renslayer", image: "Ravonna Renslayer.jpg" },
  { name: "Red Guardian", image: "Red Guardian.jpg" },
  { name: "Red Hulk", image: "Red Hulk.jpg" },
  { name: "Red Shift", image: "Red Shift.jpg" },
  { name: "Red Skull", image: "Red Skull.jpg" },
  { name: "Redwing", image: "Redwing.jpg" },
  { name: "Rescue", image: "Rescue.jpg" },
  { name: "Rhino", image: "Rhino.jpg" },
  { name: "Rocket and Groot", image: "Rocket and Groot.jpg" },
  { name: "Rocket Raccoon", image: "Rocket Raccoon.jpg" },
  { name: "Rockslide", image: "Rockslide.jpg" },
  { name: "Rogue", image: "Rogue.jpg" },
  { name: "Ronan the Accuser", image: "Ronan the Accuser.jpg" },
  { name: "Sabretooth", image: "Sabretooth.jpg" },
  { name: "Sage", image: "Sage.jpg" },
  { name: "Sam Wilson Captain America", image: "Sam Wilson Captain America.jpg" },
  { name: "Sandman", image: "Sandman.jpg" },
  { name: "Sasquatch", image: "Sasquatch.jpg" },
  { name: "Sauron", image: "Sauron.jpg" },
  { name: "Scarlet Spider", image: "Scarlet Spider.jpg" },
  { name: "Scarlet Witch", image: "Scarlet Witch.jpg" },
  { name: "Scorn", image: "Scorn.jpg" },
  { name: "Scorpion", image: "Scorpion.jpg" },
  { name: "Scream", image: "Scream.jpg" },
  { name: "Sebastian Shaw", image: "Sebastian Shaw.jpg" },
  { name: "Selene", image: "Selene.jpg" },
  { name: "Sentinel", image: "Sentinel.jpg" },
  { name: "Sentry", image: "Sentry.jpg" },
  { name: "Sera", image: "Sera.jpg" },
  { name: "Sersi", image: "Sersi.jpg" },
  { name: "Shadow King", image: "Shadow King.jpg" },
  { name: "Shang-Chi", image: "Shang-Chi.jpg" },
  { name: "Shang-Chi, Master of the Rings", image: "Shang-Chi, Master of the Rings.jpg" },
  { name: "Shanna", image: "Shanna.jpg" },
  { name: "She-Hulk", image: "She-Hulk.jpg" },
  { name: "Shocker", image: "Shocker.jpg" },
  { name: "Shou-Lao the Undying", image: "Shou-Lao the Undying.jpg" },
  { name: "Shuri", image: "Shuri.jpg" },
  { name: "Silk", image: "Silk.jpg" },
  { name: "Silver Sable", image: "Silver Sable.jpg" },
  { name: "Silver Samurai", image: "Silver Samurai.jpg" },
  { name: "Silver Surfer", image: "Silver Surfer.jpg" },
  { name: "Silver Surfer First Steps", image: "Silver Surfer First Steps.jpg" },
  { name: "Skaar", image: "Skaar.jpg" },
  { name: "Snowguard", image: "Snowguard.jpg" },
  { name: "Sparky", image: "Sparky.jpg" },
  { name: "Spectrum", image: "Spectrum.jpg" },
  { name: "Speed", image: "Speed.jpg" },
  { name: "Spider-Ham", image: "Spider-Ham.jpg" },
  { name: "Spider-Man", image: "Spider-Man.jpg" },
  { name: "Spider-Man 2099", image: "Spider-Man 2099.jpg" },
  { name: "Spider-Man Noir", image: "Spider-Man Noir.jpg" },
  { name: "Spider-Punk", image: "Spider-Punk.jpg" },
  { name: "Spider-Woman", image: "Spider-Woman.jpg" },
  { name: "Squirrel Girl", image: "Squirrel Girl.jpg" },
  { name: "Star-Lord", image: "Star-Lord.jpg" },
  { name: "Star-Lord, Master of the Sun", image: "Star-Lord, Master of the Sun.jpg" },
  { name: "Starbrand", image: "Starbrand.jpg" },
  { name: "Stardust", image: "Stardust.jpg" },
  { name: "Stature", image: "Stature.jpg" },
  { name: "Stegron", image: "Stegron.jpg" },
  { name: "Storm", image: "Storm.jpg" },
  { name: "Strange Supreme", image: "Strange Supreme.jpg" },
  { name: "Strong Guy", image: "Strong Guy.jpg" },
  { name: "Sunspot", image: "Sunspot.jpg" },
  { name: "Super-Adaptoid", image: "Super-Adaptoid.jpg" },
  { name: "Super-Skrull", image: "Super-Skrull.jpg" },
  { name: "Supergiant", image: "Supergiant.jpg" },
  { name: "Superior Spider-Man", image: "Superior Spider-Man.jpg" },
  { name: "Surge", image: "Surge.jpg" },
  { name: "Surtur", image: "Surtur.jpg" },
  { name: "Swarm", image: "Swarm.jpg" },
  { name: "Sword Master", image: "Sword Master.jpg" },
  { name: "Symbiote Spider-Man", image: "Symbiote Spider-Man.jpg" },
  { name: "Taskmaster", image: "Taskmaster.jpg" },
  { name: "Terrax the Tamer", image: "Terrax the Tamer.jpg" },
  { name: "Thaddeus Ross", image: "Thaddeus Ross.jpg" },
  { name: "Thanos", image: "Thanos.jpg" },
  { name: "The Ancient One", image: "The Ancient One.jpg" },
  { name: "The Collector", image: "The Collector.jpg" },
  { name: "The Fallen One", image: "The Fallen One.jpg" },
  { name: "The First Ghost Rider", image: "The First Ghost Rider.jpg" },
  { name: "The Hood", image: "The Hood.jpg" },
  { name: "The Hunger", image: "The Hunger.jpg" },
  { name: "The Infinaut", image: "The Infinaut.jpg" },
  { name: "The Living Tribunal", image: "The Living Tribunal.jpg" },
  { name: "The Thing", image: "The Thing.jpg" },
  { name: "The Thing First Steps", image: "The Thing First Steps.jpg" },
  { name: "Thena", image: "Thena.jpg" },
  { name: "Thor", image: "Thor.jpg" },
  { name: "Titania", image: "Titania.jpg" },
  { name: "Topaz", image: "Topaz.jpg" },
  { name: "Toxie Doxie", image: "Toxie Doxie.jpg" },
  { name: "Toxin", image: "Toxin.jpg" },
  { name: "Typhoid Mary", image: "Typhoid Mary.jpg" },
  { name: "U.S. Agent", image: "U.S. Agent.jpg" },
  { name: "Uatu the Watcher", image: "Uatu the Watcher.jpg" },
  { name: "Ultron", image: "Ultron.jpg" },
  { name: "Uncle Ben", image: "Uncle Ben.jpg" },
  { name: "Valentina", image: "Valentina.jpg" },
  { name: "Valkyrie", image: "Valkyrie.jpg" },
  { name: "Venom", image: "Venom.jpg" },
  { name: "Victoria Hand", image: "Victoria Hand.jpg" },
  { name: "Viper", image: "Viper.jpg" },
  { name: "Vision", image: "Vision.jpg" },
  { name: "Viv Vision", image: "Viv Vision.jpg" },
  { name: "Vulture", image: "Vulture.jpg" },
  { name: "Wade Wilson", image: "Wade Wilson.jpg" },
  { name: "War Machine", image: "War Machine.jpg" },
  { name: "Warlock", image: "Warlock.jpg" },
  { name: "Warpath", image: "Warpath.jpg" },
  { name: "Wasp", image: "Wasp.jpg" },
  { name: "Wave", image: "Wave.jpg" },
  { name: "Weapon H", image: "Weapon H.jpg" },
  { name: "Weapon X Wolverine", image: "Weapon X Wolverine.jpg" },
  { name: "Web Sling", image: "Web Sling.jpg" },
  { name: "Werewolf By Night", image: "Werewolf By Night.jpg" },
  { name: "White Queen", image: "White Queen.jpg" },
  { name: "White Tiger", image: "White Tiger.jpg" },
  { name: "White Widow", image: "White Widow.jpg" },
  { name: "Wiccan", image: "Wiccan.jpg" },
  { name: "Wild Child", image: "Wild Child.jpg" },
  { name: "Wolfsbane", image: "Wolfsbane.jpg" },
  { name: "Wolverine", image: "Wolverine.jpg" },
  { name: "Wong", image: "Wong.jpg" },
  { name: "X-23", image: "X-23.jpg" },
  { name: "Xorn", image: "Xorn.jpg" },
  { name: "Yellowjacket", image: "Yellowjacket.jpg" },
  { name: "Yondu", image: "Yondu.jpg" },
  { name: "Zabu", image: "Zabu.jpg" },
  { name: "Zero", image: "Zero.jpg" },
  { name: "Zombie Captain Marvel", image: "Zombie Captain Marvel.jpg" },
  { name: "Zombie Galacti", image: "Zombie Galacti.jpg" },
  { name: "Zombie Giant-Man", image: "Zombie Giant-Man.jpg" },
  { name: "Zombie Mister Fantastic", image: "Zombie Mister Fantastic.jpg" },
  { name: "Zombie Power Man", image: "Zombie Power Man.jpg" },
  { name: "Zombie Scarlet Witch", image: "Zombie Scarlet Witch.jpg" },
  { name: "Zombie Sentry", image: "Zombie Sentry.jpg" },
  { name: "Jack Flag", image: "Jack Flag.jpg" }

];

const cards = cardDatabase.map(c => c.name);
