const cardDatabase = [
  { name: "Abomination", cost: 5, power: 9, tags: ["starter","no-ability","afflict","no-ability-buff","highevo","wind10","monsters","villains"] },
  { name: "Absorbing Man", cost: 4, power: 5, tags: ["series3","on-reveal","wongreveal","effect-multiplier","text-copy","wind11","villains"] },
  { name: "Adam Warlock", cost: 2, power: 0, tags: ["series3","endofturn","end-of-turn-combo","zombie-galacti","draw","scaler","winning","guardians","wind12"] },
  { name: "Adamantium Infusion", cost: 4, power: 0, tags: ["series5","on-reveal","destroy","wongreveal","spells","nimrod-phoenix","summon","double-power","give-power"] },
  { name: "Agamotto", cost: 5, power: 10, tags: ["series5","gamestart","move","spells","card-generation","arishem-thanos","card-copy","self-buff","transform","deck-generator","draw","disruption","unique-card-creation","magicians"] },
  { name: "Agatha Harkness", cost: 6, power: 12, tags: ["series3","gamestart","zero-downsides","wind18","magicians"] },
  { name: "Agony", cost: 1, power: 2, tags: ["series4","trigger-card","merge","buff","spider-verse","symbiotes","villains"] },
  { name: "Air-Walker", cost: 3, power: 4, tags: ["series4","trigger-card","destroy","fantomex","summon"] },
  { name: "Aero", cost: 5, power: 9, tags: ["series3","on-reveal","move","scream","disruption","agents-of-atlas"] },
  { name: "Ajax", cost: 5, power: 7, tags: ["series5","ongoing","afflict","villains"] },
  { name: "Agent 13", cost: 1, power: 3, tags: ["series2","on-reveal","card-generation","hand-gen","random-card-pool","shield"] },
  { name: "Agent Coulson", cost: 3, power: 5, tags: ["series3","on-reveal","card-generation","hand-gen","random-card-pool","shield","wind9"] },
  { name: "Agent Venom", cost: 2, power: 5, tags: ["series5","on-reveal","set-power","spider-verse","thunderbolts","symbiotes"] },
  { name: "America Chavez", cost: 1, power: 2, tags: ["series1","on-reveal","buff","give-power","young-avengers","west-coast-avengers","wind9"] },
  { name: "Angel", cost: 2, power: 4, tags: ["series1","trigger-card","destroy","summon","xmen","wind3"] },
  { name: "Angela", cost: 2, power: 3, tags: ["series1","trigger-card","shou-lao","scaler","asgardians","wind2"] },
  { name: "Annihilus", cost: 5, power: 8, tags: ["series4","on-reveal","clog","destroy","werewolf-sentry","disruption","monsters","villains"] },
  { name: "Ant-Man", cost: 1, power: 1, tags: ["recruit-pass","ongoing","zoo","ongoing-combo","full-location","avengers","future-foundation","west-coast-avengers","wind4","geniuses","animal-themed"] },
  { name: "Anti-Venom", cost: 4, power: 7, tags: ["series5","on-reveal","cost-reduction","set-power","symbiotes","wind12","spider-verse"] },
  { name: "Apocalypse", cost: 6, power: 9, tags: ["series1","trigger-card","discard","revive","scaler","horsemen","wind18","villains"] },
  { name: "Alioth", cost: 6, power: 7, tags: ["series5","on-reveal","tech","arishem-thanos","disruption","text-disruption","cosmic-entities","monsters"] },
  { name: "Araña", cost: 1, power: 2, tags: ["series5","activate","move","buff","give-power","animal-themed"] },
  { name: "Archangel Horseman of Death", cost: 2, power: 4, tags: ["series5","objective","destroy","summon","give-power","xmen","horsemen","x-force","villains"] },
  { name: "Arishem", cost: 7, power: 7, tags: ["series5","gamestart","card-generation","arishem-thanos","energy-ramp","deck-generator","random-card-pool","celestial-eternals","wind6","wind10","cosmic-entities"] },
  { name: "Arnim Zola", cost: 6, power: 0, tags: ["series3","on-reveal","destroy","wongreveal","card-generation","negative","nimrod-phoenix","card-copy","board-generator","hydra","geniuses","robots-cyborgs","villains"] },
  { name: "Armor", cost: 2, power: 3, tags: ["series1","ongoing","ongoing-combo","tech","wind1","wind8"] },
  { name: "Ares", cost: 4, power: 7, tags: ["series5","on-reveal","skaar","self-buff","dark-avengers"] },
  { name: "Askani'son", cost: 2, power: 3, tags: ["series4","activate","card-generation","priority-control","board-generator","winning","random-card-pool","x-force"] },
  { name: "Astral Projection", cost: 3, power: 0, tags: ["series4","on-reveal","spells","text-copy"] },
  { name: "Attuma", cost: 4, power: 10, tags: ["series3","endofturn","zero-downsides","destroy","atlanteans","wind3","villains"] },
  { name: "Aunt May", cost: 2, power: 4, tags: ["series5","endofturn","move","cost-reduction","give-power"] },
  { name: "Aurora", cost: 6, power: 5, tags: ["series5","on-reveal","buff","aurora","multi-location-power","give-power","wind19"] },
  { name: "Awesome Andy", cost: 2, power: 3, tags: ["series4","activate","buff","multi-location-power","give-power","robots-cyborgs"] },
  { name: "Baron Mordo", cost: 2, power: 3, tags: ["series3","on-reveal","mill","disruption","wind15","magicians","villains"] },
  { name: "Baron Zemo", cost: 3, power: 5, tags: ["series5","on-reveal","mill","summon","disruption","thunderbolts","hydra","wind16","villains"] },
  { name: "Bast", cost: 1, power: 1, tags: ["series3","on-reveal","set-power","wakanda"] },
  { name: "Bastion", cost: 4, power: 3, tags: ["series5","on-reveal","card-generation","hand-gen","card-copy","cost-reduction","set-power","robots-cyborgs","villains"] },
  { name: "Batroc the Leaper", cost: 1, power: 2, tags: ["series4","trigger-card","move","mini-movers","scaler","villains"] },
  { name: "Beast", cost: 3, power: 5, tags: ["series3","on-reveal","bounce","cost-reduction","xmen","defenders","illuminati","wind11","wind17","geniuses"] },
  { name: "Beta Ray Bill", cost: 4, power: 6, tags: ["series4","on-reveal","card-generation","hammer-bros","deck-generator","double-power","self-buff","unique-card-creation","asgardians","guardians","annihilators","wind4"] },
  { name: "Bishop", cost: 3, power: 2, tags: ["series1","trigger-card","zoo","bounce","scaler","xmen"] },
  { name: "Black Bolt", cost: 5, power: 8, tags: ["series3","on-reveal","discard","mill","disruption","inhumans","illuminati","wind1"] },
  { name: "Black Cat", cost: 1, power: 4, tags: ["series3","endofturn","zero-downsides","discard","spider-verse","midnight-sons","animal-themed","antiheroes"] },
  { name: "Black Knight", cost: 1, power: 2, tags: ["series4","trigger-card","discard","card-generation","hand-gen","unique-card-creation","avengers"] },
  { name: "Black Panther", cost: 5, power: 5, tags: ["series3","on-reveal","buff","wongreveal","double-power","self-buff","avengers","wakanda","illuminati","wind13","geniuses","animal-themed"] },
  { name: "Black Swan", cost: 2, power: 3, tags: ["series5","activate","zoo","cost-reduction","black-order","animal-themed","villains"] },
  { name: "Black Widow", cost: 3, power: 3, tags: ["series3","activate","card-generation","hand-gen","mill","disruption","unique-card-creation","avengers","shield","marvel-knights","wind5","animal-themed"] },
  { name: "Blade", cost: 1, power: 3, tags: ["series1","on-reveal","discard","fantomex","midnight-sons","antiheroes"] },
  { name: "Blink", cost: 5, power: 8, tags: ["series5","on-reveal","energy-ramp","summon","wind10"] },
  { name: "Blob", cost: 6, power: 0, tags: ["series4","on-reveal","merge","self-buff","brotherhood","monsters","villains"] },
  { name: "Blue Marvel", cost: 5, power: 3, tags: ["recruit-pass","ongoing","zoo","multi-location-power","wind12"] },
  { name: "Boomerang", cost: 2, power: 2, tags: ["series5","activate","trigger-card","afflict","bounce","scaler","self-buff","power-steal","spider-verse","sinister-six","villains"] },
  { name: "Brood", cost: 3, power: 2, tags: ["series3","on-reveal","no-ability-buff","buff","card-generation","surfer","board-generator","unique-card-creation","monsters","villains"] },  
  { name: "Bruce Banner", cost: 2, power: 1, tags: ["series5","endofturn","card-generation","end-of-turn-combo","transform","unspent-energy","avengers","geniuses"] },
  { name: "Bucky Barnes", cost: 2, power: 2, tags: ["series2","trigger-card","destroy","card-generation","board-generator","unique-card-creation","thunderbolts","wind14"] },
  { name: "Bullseye", cost: 3, power: 2, tags: ["series5","activate","discard","afflict","dark-avengers","villains"] },
  { name: "Cable", cost: 2, power: 4, tags: ["series1","on-reveal","mill","draw","disruption","x-force","wind8","wind15","robots-cyborgs"] },
  { name: "Caliban Horseman of Pestilence", cost: 3, power: 4, tags: ["series5","objective","afflict","horsemen","monsters","villains"] },
  { name: "Caiera", cost: 3, power: 5, tags: ["series5","ongoing","zoo","tech"] },
  { name: "Cannonball", cost: 5, power: 5, tags: ["series4","on-reveal","clog","destroy","move","card-generation","board-generator","disruption","new-mutants","x-force","wind3"] },
  { name: "Captain America", cost: 3, power: 3, tags: ["series1","ongoing","ongoing-combo","avengers","new-avengers"] },
  { name: "Captain Carter", cost: 3, power: 2, tags: ["series5","ongoing","buff","ongoing-combo","surfer","row-interaction","avengers"] },
  { name: "Captain Marvel", cost: 4, power: 6, tags: ["series3","endofgame","move","winning","avengers"] },
  { name: "Carnage", cost: 2, power: 2, tags: ["series1","on-reveal","destroy","self-buff","spider-verse","symbiotes","villains"] },
  { name: "Cassandra Nova", cost: 3, power: 0, tags: ["series5","on-reveal","afflict","self-buff","power-steal","wind14","villains"] },
  { name: "Cerebro", cost: 3, power: 0, tags: ["series3","ongoing","ongoing-combo","multi-location-power"] },
  { name: "Chamber", cost: 2, power: 1, tags: ["series5","activate","self-buff"] },
  { name: "Chameleon", cost: 3, power: 3, tags: ["series4","on-reveal","effect-multiplier","text-copy","spider-verse","sinister-six","villains"] },
  { name: "Clea", cost: 1, power: 3, tags: ["series5","trigger-card","afflict","card-generation","hand-gen","zoo","buff","spells","unique-card-creation","magicians"] },
  { name: "Cloak", cost: 2, power: 4, tags: ["series2","on-reveal","move","marvel-knights","wind3"] },
  { name: "Cobra", cost: 2, power: 3, tags: ["series4","activate","destroy","tech","card-generation","animal-themed","villains"] },
  { name: "Colleen Wing", cost: 2, power: 4, tags: ["series3","on-reveal","discard","heroes-for-hire"] },
  { name: "Colonel America", cost: 3, power: 4, tags: ["series5","ongoing","discard","avengers","new-avengers"] },
  { name: "Colossus", cost: 2, power: 4, tags: ["recruit-pass","ongoing","xmen"] },
  { name: "Copycat", cost: 3, power: 5, tags: ["series5","trigger-card","effect-multiplier","text-copy","wind9","wind11"] },
  { name: "Corvus Glaive", cost: 3, power: 5, tags: ["series4","on-reveal","energy-ramp","summon","discard","black-order","villains"] },
  { name: "Cosmic Ghost Rider", cost: 5, power: 6, tags: ["series5","on-reveal","tech","arishem-thanos","disruption","row-interaction","text-disruption","antiheroes"] },
  { name: "Cosmo", cost: 3, power: 3, tags: ["series1","ongoing","ongoing-combo","tech","disruption","guardians","wind5","animals"] },
  { name: "Crossbones", cost: 4, power: 10, tags: ["series3","trigger-card","skaar","zero-downsides","thunderbolts","hydra","wind10","villains"] },
  { name: "Crystal", cost: 3, power: 6, tags: ["series3","on-reveal","draw","inhumans"] },
  { name: "Cull Obsidian", cost: 4, power: 10, tags: ["series4","trigger-card","zero-downsides","zoo","black-order","wind2","wind9","monsters","villains"] },
  { name: "Cyclops", cost: 3, power: 5, tags: ["starter","no-ability","afflict","no-ability-buff","highevo","unspent-energy","xmen","wind4"] },
  { name: "Dagger", cost: 2, power: 2, tags: ["series3","trigger-card","move","scaler","marvel-knights","wind7"] },
  { name: "Daken", cost: 3, power: 4, tags: ["series4","on-reveal","discard","destroy","card-generation","hand-gen","double-power","self-buff","unique-card-creation","dark-avengers"] },
  { name: "Danger", cost: 4, power: 6, tags: ["series4","activate","destroy","disruption","robots-cyborgs","villains"] },
  { name: "Daredevil", cost: 2, power: 3, tags: ["series3","trigger-card","defenders","marvel-knights"] },  
  { name: "Darkhawk", cost: 5, power: 3, tags: ["series4","ongoing","wind18","animal-themed"] },
  { name: "Dazzler", cost: 2, power: 2, tags: ["series3","ongoing","zoo","full-location","xmen","wind5"] },
  { name: "Deadpool", cost: 1, power: 1, tags: ["series3","trigger-card","destroy","revive","scaler","double-power","thunderbolts","x-force","wind2","wind8","antiheroes"] },
  { name: "Deafening Chord", cost: 1, power: 0, tags: ["series4","on-reveal","tech","spells","disruption","text-disruption"] },
  { name: "Death", cost: 8, power: 12, tags: ["series3","trigger-card","destroy","cost-reduction","wind17","cosmic-entities"] },
  { name: "Deathlok", cost: 3, power: 6, tags: ["series1","on-reveal","destroy","robots-cyborgs"] },
  { name: "Debrii", cost: 3, power: 7, tags: ["series3","on-reveal","no-ability-buff","card-generation","priority-control","board-generator"] },
  { name: "Destroyer", cost: 6, power: 18, tags: ["series3","on-reveal","zero-downsides","destroy","nimrod-phoenix","wind1"] },
  { name: "Devil Dinosaur", cost: 5, power: 4, tags: ["series1","ongoing","card-generation","hand-gen","animals","monsters"] },
  { name: "Diamondback", cost: 3, power: 3, tags: ["series5","ongoing","afflict","effect-multiplier","animal-themed"] },
  { name: "Doctor Doom", cost: 6, power: 5, tags: ["series3","on-reveal","no-ability-buff","wongreveal","card-generation","lockdown","board-generator","unique-card-creation","cabal","wind15","wind17","magicians","geniuses","villains"] },
  { name: "Doctor Doom 2099", cost: 4, power: 6, tags: ["series5","endofturn","card-generation","end-of-turn-combo","board-generator","multi-location-power","unique-card-creation","play-requirement","geniuses","villains"] },
  { name: "Doctor Octopus", cost: 4, power: 8, tags: ["series3","on-reveal","clog","mill","zero-downsides","summon","disruption","sinister-six","wind8","wind17","spider-verse","geniuses","villains"] },
  { name: "Doctor Strange", cost: 2, power: 4, tags: ["series1","on-reveal","move","avengers","midnight-sons","defenders","illuminati","new-avengers","wind11","wind17","magicians"] },
  { name: "Domino", cost: 2, power: 4, tags: ["series1","trigger-card","wiccan","draw","x-force"] },
  { name: "Dormammu", cost: 7, power: 13, tags: ["series5","gamestart","afflict","destroy","card-generation","hand-gen","spells","self-buff","summon","scaler","unique-card-creation","power-steal","magicians","cosmic-entities","monsters","villains"] },
  { name: "Dracula", cost: 4, power: 1, tags: ["series3","endofgame","discard","self-buff","monsters","villains"] },
  { name: "Dragon Lord", cost: 5, power: 5, tags: ["series4","on-reveal","summon","animal-themed"] },
  { name: "Dragon of the Moon", cost: 3, power: 4, tags: ["series5","on-reveal","afflict","self-buff","power-steal","animals","monsters"] },
  { name: "Drax", cost: 4, power: 5, tags: ["series3","on-reveal","self-buff","guardians","wind16"] },
  { name: "Drax, Avatar Of Life", cost: 3, power: 3, tags: ["series5","endofturn","move","end-of-turn-combo","scaler","winning","guardians"] },
  { name: "Ebony Maw", cost: 1, power: 7, tags: ["series2","ongoing","zero-downsides","black-order","wind16","villains"] },
  { name: "Echo", cost: 1, power: 2, tags: ["series3","trigger-card","tech","text-disruption","new-avengers"] },
  { name: "Electro", cost: 3, power: 5, tags: ["series3","ongoing","on-reveal","zero-downsides","energy-ramp","spider-verse","sinister-six","villains"] },
  { name: "Elektra", cost: 1, power: 2, tags: ["series1","on-reveal","tech","disruption","destroy","thunderbolts","wind1","antiheroes"] },
  { name: "Elixir", cost: 2, power: 3, tags: ["series5","on-reveal","destroy","summon"] },
  { name: "Elsa Bloodstone", cost: 3, power: 5, tags: ["series4","trigger-card","buff","shou-lao","multi-location-power","give-power","full-location","midnight-sons","wind6"] },
  { name: "Emperor Hulkling", cost: 6, power: 12, tags: ["series5","gamestart","random-card-pool","text-copy","young-avengers"] },
  { name: "Enchantress", cost: 5, power: 8, tags: ["series1","on-reveal","tech","zero-downsides","disruption","text-disruption","asgardians","magicians","villains"] },
  { name: "En Sabah Nur", cost: 4, power: 6, tags: ["series5","objective","transform","summon","row-interaction","horsemen","villains"] },
  { name: "Esme Cuckoo", cost: 3, power: 4, tags: ["series5","on-reveal","card-generation","negative","hand-gen","card-copy","cost-reduction","set-power"] },
  { name: "Eson", cost: 6, power: 10, tags: ["series5","endofturn","card-generation","arishem-thanos","hand-gen","summon","celestial-eternals","cosmic-entities"] },
  { name: "Ezekiel Sims", cost: 2, power: 2, tags: ["series5","trigger-card","move","scaler","spider-verse","animal-themed"] },
  { name: "Falcon", cost: 2, power: 3, tags: ["series3","on-reveal","bounce","avengers","animal-themed"] },  
  { name: "Fan Fei", cost: 4, power: 5, tags: ["series4","activate","move","buff","give-power"] },
  { name: "Fantasticar", cost: 4, power: 5, tags: ["series4","activate","buff","end-of-turn-combo","multi-location-power","give-power","fantastic4"] },
  { name: "Fantomex", cost: 4, power: 7, tags: ["series5","activate","discard","afflict","destroy","fantomex","row-interaction","x-force"] },
  { name: "Fastball Special", cost: 2, power: 0, tags: ["series4","on-reveal","afflict","destroy","spells","nimrod-phoenix"] },
  { name: "Fenris Wolf", cost: 3, power: 4, tags: ["series5","activate","discard","tech","summon","destroy","asgardians","animals","monsters"] },
  { name: "Fin Fang Foom", cost: 7, power: 14, tags: ["series5","on-reveal","self-buff","row-interaction","animals","monsters","villains"] },
  { name: "Firehair", cost: 2, power: 3, tags: ["series5","trigger-card","destroy","effect-multiplier"] },
  { name: "Firelord", cost: 4, power: 7, tags: ["series4","on-reveal","discard","destroy","summon"] },
  { name: "Forge", cost: 2, power: 2, tags: ["series1","on-reveal","buff","give-power","xmen","wind13","wind18","geniuses"] },
  { name: "Frigga", cost: 3, power: 3, tags: ["series5","on-reveal","card-generation","hand-gen","card-copy","asgardians"] },
  { name: "Galacta", cost: 4, power: 6, tags: ["series5","trigger-card","buff","give-power"] },
  { name: "Galactus", cost: 6, power: 6, tags: ["series5","on-reveal","destroy","winning","disruption","cosmic-entities","villains"] },
  { name: "Galactus First Steps", cost: 6, power: 11, tags: ["series5","endofturn","end-of-turn-combo","scaler","winning","cosmic-entities","villains"] },
  { name: "Gambit", cost: 3, power: 3, tags: ["series3","on-reveal","discard","destroy","wongreveal","fantomex","disruption","xmen"] },
  { name: "Gambit Horseman of Death", cost: 3, power: 5, tags: ["series5","objective","destroy","card-generation","hand-gen","tech","xmen","horsemen","villains"] },
  { name: "Gamora", cost: 5, power: 8, tags: ["recruit-pass","on-reveal","self-buff","guardians","wind9","wind13"] },
  { name: "Ghost", cost: 3, power: 4, tags: ["series3","on-reveal","tech","text-disruption","thunderbolts"] },
  { name: "Ghost Rider", cost: 4, power: 5, tags: ["series3","on-reveal","discard","summon","midnight-sons","wind18","monsters","antiheroes"] },
  { name: "Ghost-Spider", cost: 1, power: 3, tags: ["series3","on-reveal","move","wind11","spider-verse","animal-themed"] },
  { name: "Giganto", cost: 6, power: 16, tags: ["series3","trigger-card","zero-downsides","monsters"] },
  { name: "Gilgamesh", cost: 5, power: 9, tags: ["series5","on-reveal","zoo","buff","self-buff","celestial-eternals","wind19"] },
  { name: "Gladiator", cost: 3, power: 8, tags: ["series4","on-reveal","mill","zero-downsides","summon","disruption","destroy","annihilators"] },
  { name: "Goliath", cost: 2, power: 1, tags: ["series5","ongoing","ongoing-combo"] },
  { name: "Goose", cost: 2, power: 2, tags: ["series3","ongoing","tech","lockdown","wind2","animals"] },
  { name: "Gorgon", cost: 2, power: 3, tags: ["series4","ongoing","tech","card-generation","inhumans","villains"] },
  { name: "Gorr the God Butcher", cost: 6, power: 1, tags: ["series5","ongoing","negative","villains"] },
  { name: "Grand Master", cost: 2, power: 3, tags: ["series4","on-reveal","move","wongreveal","effect-multiplier","wind1","villains"] },
  { name: "Green Goblin", cost: 3, power: -4, tags: ["series3","on-reveal","clog","disruption","spider-verse","villains"] },
  { name: "Groot", cost: 3, power: 4, tags: ["series1","on-reveal","self-buff","guardians","wind5","wind17"] },
  { name: "Gwenpool", cost: 4, power: 5, tags: ["series5","on-reveal","buff","zombie-galacti","give-power","west-coast-avengers"] },
  { name: "H.E.R.B.I.E.", cost:2, power: 3, tags: ["series5","activate","no-ability-buff","zoo","buff","card-generation","aurora","energy-ramp","double-power","multi-location-power","give-power","self-buff","set-power","robots-cyborgs"] },
  { name: "Havok", cost: 2, power: 1, tags: ["series3","endofturn","end-of-turn-combo","zero-downsides","scaler","xmen"] },
  { name: "Hawkeye Kate Bishop", cost: 2, power: 3, tags: ["series5","on-reveal","clog","card-generation","hand-gen","zoo","move","wiccan","disruption","unique-card-creation","full-location","young-avengers","west-coast-avengers","animal-themed"] },
  { name: "Hawkeye", cost: 1, power: 1, tags: ["starter","on-reveal","bounce","self-buff","avengers","shield","thunderbolts","west-coast-avengers","new-avengers","animal-themed"] },
  { name: "Hazmat", cost: 3, power: 3, tags: ["series3","on-reveal","afflict","wongreveal"] },
  { name: "Headpool", cost: 1, power: 1, tags: ["series5","trigger-card","destroy","buff","revive","give-power","monsters"] },
  { name: "Heimdall", cost: 6, power: 10, tags: ["series1","on-reveal","move","asgardians","wind16"] },
  { name: "Hela", cost: 6, power: 6, tags: ["series3","on-reveal","discard","summon","asgardians","magicians","villains"] },
  { name: "Helicarrier", cost: 6, power: 12, tags: ["series3","trigger-card","discard","card-generation","hand-gen","random-card-pool","shield"] },
  { name: "Hellcow", cost: 4, power: 7, tags: ["series3","activate","discard","wind6","wind11","animals","monsters","villains"] },
  { name: "Hellion", cost: 5, power: 8, tags: ["series4","on-reveal","move"] },
  { name: "Hercules", cost: 3, power: 5, tags: ["series3","trigger-card","move","avengers","wind6"] },
  { name: "High Evolutionary", cost: 4, power: 7, tags: ["series5","gamestart","afflict","highevo","transform","geniuses","villains"] },
  { name: "Hit-Monkey", cost: 3, power: 3, tags: ["series4","on-reveal","self-buff","wind3","wind19","animals"] },
  { name: "Hobgoblin", cost: 5, power: -8, tags: ["series2","on-reveal","clog","disruption","spider-verse","sinister-six","villains"] },
  { name: "Hope Summers", cost: 3, power: 4, tags: ["series5","trigger-card","surfer","energy-ramp"] },
  { name: "Howard the Duck", cost: 1, power: 2, tags: ["series3","ongoing","guardians","animals"] },
  { name: "Hulk", cost: 6, power: 14, tags: ["starter","no-ability","no-ability-buff","highevo","unspent-energy","avengers","defenders","wind3"] },
  { name: "Hulkbuster", cost: 2, power: 3, tags: ["series1","on-reveal","merge","buff","wind13"] },
  { name: "Human Torch", cost: 3, power: 2, tags: ["series3","trigger-card","move","nimrod-phoenix","scaler","double-power","fantastic4","future-foundation"] },
  { name: "Human Torch First Steps", cost: 3, power: 2, tags: ["series5","endofturn","buff","scaler","double-power","full-location","fantastic4","future-foundation"] },
  { name: "Hydra Bob", cost: 1, power: 4, tags: ["series5","endofturn","zoo","move","priority-control","aurora","hydra","wind8","antiheroes"] },
  { name: "Hydra Stomper", cost: 3, power: 3, tags: ["series5","ongoing","move","mini-movers","scaler"] },
  { name: "Hydro-Man", cost: 5, power: 8, tags: ["series4","on-reveal","cost-reduction","villains"] },
  { name: "Iceman", cost: 1, power: 2, tags: ["series2","on-reveal","zoo","disruption","xmen"] },
  { name: "Infinity Ultron", cost: 5, power: 6, tags: ["series5","on-reveal","card-generation","hand-gen","move","buff","effect-multiplier","self-buff","summon","board-generator","double-power","multi-location-power","disruption","unique-card-creation","give-power","set-power","full-location","robots-cyborgs","villains"] },
  { name: "Invisible Woman", cost: 2, power: 4, tags: ["series3","ongoing","ongoing-combo","delayed-reveal","fantastic4","future-foundation"] },
  { name: "Invisible Woman First Steps", cost: 3, power: 3, tags: ["series5","activate","end-of-turn-combo","fantastic4","future-foundation"] },
  { name: "Ikari", cost: 4, power: 12, tags: ["series4","trigger-card","afflict"] },
  { name: "Iron Fist", cost: 1, power: 3, tags: ["series1","on-reveal","move","midnight-sons","defenders","heroes-for-hire","new-avengers","wind3","wind12"] },
  { name: "Iron Lad", cost: 4, power: 7, tags: ["series4","on-reveal","wongreveal","ongoing-combo","effect-multiplier","text-copy","young-avengers","wind7"] },
  { name: "Iron Man", cost: 5, power: 0, tags: ["starter","ongoing","ongoing-combo","negative","avengers","illuminati","west-coast-avengers","new-avengers","wind7","geniuses"] },
  { name: "Iron Patriot", cost: 2, power: 3, tags: ["series5","on-reveal","card-generation","priority-control","cost-reduction","winning","random-card-pool","dark-avengers","cabal"] },
  { name: "Ironheart", cost: 3, power: 0, tags: ["recruit-pass","on-reveal","buff","wongreveal","multi-location-power","give-power","wind11","geniuses"] },
  { name: "Isca the Unbeaten", cost: 4, power: 3, tags: ["series5","endofturn","end-of-turn-combo","aurora","scaler","double-power","winning"] },
  { name: "Jane Foster Mighty Thor", cost: 5, power: 9, tags: ["series3","on-reveal","negative","hammer-bros","draw","asgardians","wind4"] },
  { name: "Jack Flag", cost: 3, power: 3, tags: ["series5","ongoing","buff"] },
  { name: "Jean Grey", cost: 3, power: 4, tags: ["series3","ongoing","tech","lockdown","disruption","xmen","wind15"] },
  { name: "Jeff!", cost: 2, power: 4, tags: ["series5","moveable","move","lockdown","west-coast-avengers","wind9","animals"] },
  { name: "Jeff the Baby Dolphin!?", cost: 2, power: 2, tags: ["series5","moveable","trigger-card","move","buff","multi-location-power","give-power","west-coast-avengers","animals"] },
  { name: "Jennifer Kale", cost: 2, power: 3, tags: ["series4","activate","energy-ramp","wind18","magicians"] },
  { name: "Jessica Jones", cost: 4, power: 5, tags: ["series0","on-reveal","self-buff","defenders"] },
  { name: "Jim Hammond Human Torch", cost: 1, power: 2, tags: ["series5","startofturn","energy-ramp","scaler","robots-cyborgs"] },
  { name: "Joaquin Torres Falcon II", cost: 2, power: 3, tags: ["series5","ongoing","bounce","spells","effect-multiplier","animal-themed"] },
  { name: "Jocasta", cost: 3, power: 3, tags: ["series5","activate","end-of-turn-combo","effect-multiplier","robots-cyborgs"] },
  { name: "Jubilee", cost: 4, power: 1, tags: ["series2","on-reveal","summon","xmen"] },
  { name: "Jubilee Silver Surfer", cost: 4, power: 3, tags: ["series5","trigger-card","buff","zombie-galacti","give-power","xmen"] },
  { name: "Juggernaut", cost: 4, power: 5, tags: ["series3","on-reveal","move","tech","scream","priority-control","disruption","thunderbolts","villains"] },
  { name: "Juggernaut Horseman of War", cost: 2, power: 2, tags: ["series5","objective","self-buff","horsemen","villains"] },
  { name: "Ka-Zar", cost: 4, power: 6, tags: ["series0","ongoing","zoo","multi-location-power"] },
  { name: "Kahhori", cost: 4, power: 7, tags: ["series5","on-reveal","card-generation","hand-gen","buff","multi-location-power","give-power"] },
  { name: "Kang", cost: 3, power: 4, tags: ["series5","gamestart","card-generation","deck-generator","random-card-pool","geniuses","villains"] },
   { name: "Karen Page", cost: 4, power: 6, tags: ["series5","on-reveal","buff","multi-location-power","give-power"] },
  { name: "Khonshu", cost: 6, power: 5, tags: ["series5","on-reveal","discard","transform","summon","revive","scaler","set-power","animal-themed"] },  
  { name: "Kid Omega", cost: 2, power: 1, tags: ["series5","activate","destroy","nimrod-phoenix","self-buff","west-coast-avengers"] },
  { name: "Killmonger", cost: 3, power: 3, tags: ["series2","on-reveal","tech","disruption","destroy","wakanda","villains"] },
  { name: "King Eitri", cost: 1, power: 3, tags: ["series4","activate","card-generation","hammer-bros","draw","asgardians"] },
  { name: "Kingpin", cost: 1, power: 3, tags: ["series3","trigger-card","afflict","move","scream","wind5","wind10","spider-verse","villains"] },
  { name: "Kitty Pryde", cost: 1, power: 1, tags: ["series3","startofturn","bounce","zoo","shou-lao","scaler","xmen","wind3"] },
  { name: "Klaw", cost: 5, power: 4, tags: ["series1","ongoing","ongoing-combo","lockdown","multi-location-power","villains"] },
  { name: "Knull", cost: 6, power: 0, tags: ["series3","ongoing","destroy","scaler","symbiotes","wind17","cosmic-entities","villains"] },
  { name: "Korg", cost: 1, power: 2, tags: ["series1","on-reveal","zoo","mill","card-generation","deck-generator","disruption","wind8","wind10","wind13"] },
  { name: "Kraglin", cost: 3, power: 5, tags: ["series5","on-reveal","energy-ramp","self-buff","wind18"] },
  { name: "Kraven", cost: 2, power: 3, tags: ["series1","trigger-card","move","mini-movers","scaler","sinister-six","wind5","wind10","spider-verse","animal-themed","villains"] },
  { name: "Lady Bullseye", cost: 2, power: 3, tags: ["series5","on-reveal","afflict","wongreveal","unspent-energy","villains"] },
  { name: "Lady Deathstrike", cost: 5, power: 7, tags: ["series3","on-reveal","destroy","tech","disruption","wind14","robots-cyborgs","villains"] },
  { name: "Lady Sif", cost: 3, power: 6, tags: ["series1","on-reveal","discard","asgardians"] },
  { name: "Lasher", cost: 2, power: 2, tags: ["series4","activate","afflict","buff","symbiotes","wind16","villains"] },
  { name: "Laufey", cost: 4, power: 5, tags: ["series4","on-reveal","afflict","self-buff","power-steal","villains"] },
  { name: "Leader", cost: 6, power: 5, tags: ["series3","on-reveal","wongreveal","card-generation","card-copy","wind7","geniuses","villains"] },
  { name: "Leech", cost: 4, power: 4, tags: ["series2","on-reveal","tech","disruption","text-disruption","monsters","villains"] },
  { name: "Legion", cost: 5, power: 7, tags: ["series4","on-reveal","tech","lockdown","location","wind8"] },
  { name: "Lin Lie Iron Fist", cost: 2, power: 3, tags: ["series5","on-reveal","card-generation","hand-gen","move","board-generator","unique-card-creation"] },
  { name: "Lizard", cost: 2, power: 6, tags: ["series1","ongoing","ongoing-combo","priority-control","zero-downsides","full-location","spider-verse","sinister-six","animal-themed","monsters","villains"] },
  { name: "Lockheed", cost: 2, power: 2, tags: ["series5","endofturn","afflict","zoo","end-of-turn-combo","play-requirement","animals"] },
  { name: "Lockjaw", cost: 2, power: 3, tags: ["series3","activate","hammer-bros","summon","inhumans","animals"] },
  { name: "Loki", cost: 1, power: 2, tags: ["series4","on-reveal","card-generation","cost-reduction","card-copy","deck-generator","asgardians","cabal","magicians","villains","antiheroes"] },
  { name: "Luke Cage", cost: 2, power: 2, tags: ["series3","ongoing","ongoing-combo","tech","zero-downsides","afflict","row-interaction","thunderbolts","defenders","marvel-knights","heroes-for-hire","new-avengers","wind5"] },
  { name: "Luna Snow", cost: 3, power: 6, tags: ["series5","on-reveal","card-generation","energy-ramp","board-generator","unique-card-creation","full-location","agents-of-atlas"] },
  { name: "M'Baku", cost: 1, power: 3, tags: ["series3","endofgame","zoo","summon","wakanda","animal-themed"] },
  { name: "M.O.D.O.K.", cost: 5, power: 7, tags: ["series3","on-reveal","discard","wind18","geniuses","villains"] },
  { name: "Mad Thinker", cost: 1, power: 2, tags: ["series4","startofturn","card-generation","hand-gen","scaler","villains"] },
  { name: "Madame Web", cost: 2, power: 1, tags: ["series5","ongoing","move","spider-verse","animal-themed"] },
  { name: "Magik", cost: 3, power: 2, tags: ["series3","on-reveal","negative","location","xmen","midnight-sons","new-mutants","wind10","magicians"] },
  { name: "Magneto", cost: 6, power: 12, tags: ["series3","on-reveal","move","scream","disruption","brotherhood"] },
  { name: "Magus", cost: 2, power: 4, tags: ["series5","activate","text-copy","unspent-energy","villains"] },
  { name: "Majestic Wingbeat", cost: 1, power: 0, tags: ["series4","on-reveal","buff","spells","zombie-galacti","cost-reduction","give-power"] },  
  { name: "Major Victory", cost: 3, power: 5, tags: ["series4","on-reveal","card-generation","hand-gen","random-card-pool"] },
  { name: "Makkari", cost: 3, power: 3, tags: ["series5","endofturn","surfer","lockdown","summon","celestial-eternals"] },
  { name: "Malekith", cost: 4, power: 6, tags: ["series5","on-reveal","summon","delayed-reveal","villains"] },
  { name: "Man-Spider", cost: 5, power: 1, tags: ["series5","trigger-card","merge","scaler","double-power","self-buff","spider-verse","animal-themed","monsters"] },
  { name: "Man-Thing", cost: 4, power: 7, tags: ["series4","ongoing","afflict","thunderbolts","midnight-sons","wind13","wind15","monsters"] },
  { name: "Mantis", cost: 1, power: 3, tags: ["series1","on-reveal","card-generation","hand-gen","card-copy","guardians","wind9","animal-themed"] },
  { name: "Maria Hill", cost: 1, power: 3, tags: ["series3","on-reveal","card-generation","hand-gen","random-card-pool","shield","wind19"] },
  { name: "Marrow", cost: 2, power: 3, tags: ["series4","trigger-card","discard","afflict","destroy","fantomex","monsters"] },
  { name: "Martyr", cost: 1, power: 5, tags: ["series3","endofgame","move","zero-downsides","zoo","priority-control"] },
  { name: "Mary Jane", cost: 3, power: 3, tags: ["series5","endofturn","move","multi-location-power","give-power"] },
  { name: "Marvel Boy", cost: 3, power: 2, tags: ["series5","endofturn","zoo","buff","end-of-turn-combo","multi-location-power","give-power","young-avengers"] },
  { name: "Master Mold", cost: 2, power: 3, tags: ["series3","on-reveal","card-generation","hand-gen","mill","disruption","robots-cyborgs","villains"] },
  { name: "Maverick", cost: 3, power: 2, tags: ["series5","activate","buff","shou-lao","zombie-galacti","surfer","give-power"] },
  { name: "Maximus", cost: 2, power: 6, tags: ["series3","on-reveal","zero-downsides","draw","inhumans","wind4","wind13","wind15","wind16"] },
  { name: "Medusa", cost: 2, power: 2, tags: ["starter","on-reveal","self-buff","inhumans","future-foundation"] },
  { name: "Mercury", cost: 3, power: 4, tags: ["series4","ongoing","moveable","move","tech"] },
  { name: "Merlin", cost: 2, power: 2, tags: ["series5","startofturn","card-generation","hand-gen","energy-ramp","spells","shou-lao","werewolf-sentry","location","self-buff","transform","unique-card-creation"] },
  { name: "Miek", cost: 1, power: 1, tags: ["series4","trigger-card","discard","move","scaler","monsters","villains"] },
  { name: "Miles Morales Spider-Man", cost: 4, power: 6, tags: ["series3","trigger-card","move","mini-movers","cost-reduction","wind12","wind19","spider-verse","animal-themed"] },
  { name: "Mirage", cost: 2, power: 3, tags: ["series3","on-reveal","card-generation","hand-gen","card-copy","give-power","new-mutants","wind15"] },
  { name: "Misery", cost: 4, power: 8, tags: ["series5","on-reveal","destroy","effect-multiplier","symbiotes","villains"] },
  { name: "Mister Fantastic", cost: 3, power: 1, tags: ["series0","ongoing","ongoing-combo","multi-location-power","fantastic4","future-foundation","illuminati","geniuses"] },
  { name: "Mister Fantastic First Steps", cost: 3, power: 4, tags: ["series5","endofturn","buff","cost-reduction","give-power","fantastic4","future-foundation","illuminati","wind19","geniuses"] },
  { name: "Mister Negative", cost: 4, power: -1, tags: ["series3","on-reveal","negative","cost-reduction","wind18","villains"] },
  { name: "Mister Sinister", cost: 2, power: 2, tags: ["series1","on-reveal","no-ability-buff","buff","card-generation","board-generator","unique-card-creation","wind14","geniuses","villains"] },
  { name: "Misty Knight", cost: 1, power: 3, tags: ["starter","no-ability","no-ability-buff","highevo","unspent-energy","heroes-for-hire","robots-cyborgs"] },
  { name: "Mobius M. Mobius", cost: 3, power: 3, tags: ["series3","ongoing","tech"] },
  { name: "Mockingbird", cost: 6, power: 9, tags: ["series5","trigger-card","card-generation","hand-gen","zoo","arishem-thanos","cost-reduction","shield","west-coast-avengers","animal-themed"] },
  { name: "Moira X", cost: 1, power: 2, tags: ["series5","trigger-card","destroy","card-generation","hand-gen","card-copy"] },
  { name: "Mojo", cost: 2, power: 2, tags: ["series3","ongoing","full-location","wind9","wind12","villains"] },
  { name: "Mole Man", cost: 3, power: 4, tags: ["series4","on-reveal","card-generation","hand-gen","no-ability-buff","set-power","animal-themed","villains"] },
  { name: "Monstro", cost: 8, power: 8, tags: ["series5","trigger-card","cost-reduction","monsters"] },
  { name: "Moon Girl", cost: 4, power: 5, tags: ["series1","on-reveal","card-generation","hand-gen","card-copy","inhumans","geniuses"] },
  { name: "Moon Knight", cost: 3, power: 3, tags: ["series3","on-reveal","discard","mill","disruption","midnight-sons","marvel-knights","west-coast-avengers","wind9","antiheroes"] },
  { name: "Moondragon", cost: 2, power: 1, tags: ["series5","endofturn","end-of-turn-combo","scaler","play-requirement","guardians","animal-themed"] },
  { name: "Moonstone", cost: 4, power: 6, tags: ["series5","ongoing","ongoing-combo","thunderbolts","dark-avengers","villains"] },
  { name: "Morbius", cost: 2, power: 0, tags: ["series2","ongoing","discard","scaler","spider-verse","midnight-sons","monsters","antiheroes"] },
  { name: "Morgan le Fay", cost: 3, power: 4, tags: ["series5","on-reveal","discard","destroy","buff","revive","give-power","magicians","villains"] },
  { name: "Mother Askani", cost: 4, power: 4, tags: ["series4","on-reveal","card-generation","hand-gen","buff","card-copy","cost-reduction","give-power"] },
  { name: "Morph", cost: 3, power: 0, tags: ["series1","on-reveal","card-copy","transform","random-card-pool","wind7","wind10"] },
  { name: "Ms. Marvel", cost: 4, power: 5, tags: ["series4","ongoing","ongoing-combo","lockdown","multi-location-power","avengers","inhumans","wind4","wind7"] },
  { name: "Multiple Man", cost: 2, power: 4, tags: ["series1","trigger-card","move","card-generation","nimrod-phoenix","card-copy","board-generator","wind2","wind5","wind11"] },
  { name: "Nakia", cost: 3, power: 4, tags: ["series2","on-reveal","buff","give-power","wakanda"] },
  { name: "Mysterio", cost: 2, power: 5, tags: ["series3","activate","no-ability-buff","buff","card-generation","shou-lao","aurora","board-generator","unique-card-creation","sinister-six","wind1","spider-verse","villains"] },
  { name: "Mystique", cost: 3, power: 0, tags: ["series3","ongoing","on-reveal","ongoing-combo","negative","effect-multiplier","text-copy","brotherhood","wind4","villains"] },
  { name: "Muse", cost: 3, power: 3, tags: ["series5","ongoing","destroy","villains"] },
  { name: "Namor", cost: 4, power: 6, tags: ["series1","ongoing","defenders","illuminati","cabal","atlanteans","antiheroes"] },
  { name: "Namora", cost: 5, power: 7, tags: ["series5","on-reveal","buff","wongreveal","multi-location-power","give-power","atlanteans","wind15"] },
  { name: "Namorita", cost: 3, power: 5, tags: ["series5","trigger-card","cost-reduction"] },
  { name: "Nebula", cost: 1, power: 1, tags: ["series3","trigger-card","zoo","lockdown","scaler","guardians","robots-cyborgs"] },
  { name: "Negasonic Teenage Warhead", cost: 4, power: 4, tags: ["series3","trigger-card","tech","disruption","destroy","priority-control","wind7"] },
  { name: "Nicholas Scratch", cost: 1, power: 2, tags: ["series4","trigger-card","spells","scaler","villains"] },
  { name: "Nick Fury", cost: 4, power: 6, tags: ["series3","on-reveal","card-generation","hand-gen","random-card-pool","avengers","shield"] },
  { name: "Nico Minoru", cost: 1, power: 2, tags: ["series5","on-reveal","destroy","card-generation","bounce","hand-gen","zoo","move","buff","card-copy","location","draw","double-power","give-power","self-buff","midnight-sons","wind1","magicians"] },
  { name: "Nightcrawler", cost: 1, power: 3, tags: ["series0","moveable","zoo","move","mini-movers","xmen","wind4","wind6","wind7"] },
  { name: "Nightmare", cost: 3, power: 1, tags: ["series5","on-reveal","zero-downsides","random-card-pool","text-disruption","cosmic-entities","monsters","villains"] },
  { name: "Nimrod", cost: 5, power: 6, tags: ["series3","trigger-card","destroy","card-generation","nimrod-phoenix","card-copy","board-generator","robots-cyborgs","villains"] },
  { name: "Nocturne", cost: 3, power: 5, tags: ["series5","moveable","trigger-card","move","location","wind6","wind7"] },
  { name: "Nova", cost: 1, power: 1, tags: ["series1","trigger-card","destroy","buff","multi-location-power","give-power","guardians","wind14"] },
  { name: "Nova Frankie Raye", cost: 2, power: 3, tags: ["series5","trigger-card","buff","double-power","self-buff"] },
  { name: "Odin", cost: 6, power: 10, tags: ["series0","on-reveal","wongreveal","effect-multiplier","asgardians"] },
  { name: "Okoye", cost: 2, power: 3, tags: ["series2","on-reveal","buff","give-power","wakanda","wind11"] },
  { name: "Omega Red", cost: 4, power: 6, tags: ["series3","ongoing","ongoing-combo","multi-location-power","villains"] },
  { name: "Omega Sentinel", cost: 4, power: 3, tags: ["series4","activate","robots-cyborgs","villains"] },
  { name: "Onslaught", cost: 6, power: 8, tags: ["series1","ongoing","ongoing-combo","effect-multiplier","villains"] },
  { name: "Orka", cost: 6, power: 11, tags: ["series3","ongoing","atlanteans","wind5","wind6","animal-themed","monsters","villains"] },
  { name: "Ozymandias", cost: 5, power: 9, tags: ["series4","ongoing","no-ability-buff"] },
  { name: "Patriot", cost: 3, power: 2, tags: ["series3","ongoing","no-ability-buff","multi-location-power","young-avengers","wind11","wind17"] },
  { name: "Peni Parker", cost: 2, power: 3, tags: ["series5","on-reveal","merge","card-generation","hand-gen","buff","energy-ramp","unique-card-creation","animal-themed"] },
  { name: "Phastos", cost: 3, power: 4, tags: ["series4","on-reveal","buff","cost-reduction","give-power","celestial-eternals"] },
  { name: "Phoenix Force", cost: 4, power: 5, tags: ["series4","on-reveal","merge","destroy","move","nimrod-phoenix","cosmic-entities"] },
  { name: "Pixie", cost: 2, power: 2, tags: ["series4","on-reveal","cost-reduction","wind4","wind8"] },
  { name: "Polaris", cost: 3, power: 5, tags: ["series3","on-reveal","move","scream","disruption","xmen","wind5"] },
  { name: "Polaris Horseman of Pestilence", cost: 2, power: 2, tags: ["series5","objective","summon","xmen","horsemen","villains"] },
  { name: "Prodigy", cost: 3, power: 4, tags: ["series5","on-reveal","effect-multiplier","text-copy","row-interaction","young-avengers"] },
  { name: "Professor X", cost: 5, power: 2, tags: ["series1","ongoing","ongoing-combo","lockdown","location","disruption","xmen","illuminati"] },
  { name: "Prowler", cost: 3, power: 4, tags: ["series5","on-reveal","card-generation","hand-gen","move","buff","energy-ramp","spells","cost-reduction","unique-card-creation","give-power","spider-verse","sinister-six","villains"] },
  { name: "Proxima Midnight", cost: 4, power: 7, tags: ["series5","trigger-card","discard","summon","black-order","villains"] },
  { name: "Psylocke", cost: 2, power: 2, tags: ["series3","on-reveal","negative","energy-ramp","xmen","x-force","wind7","wind12","wind14"] },
  { name: "Punisher", cost: 3, power: 3, tags: ["starter","ongoing","ongoing-combo","thunderbolts","marvel-knights","antiheroes"] },
  { name: "Punisher War Machine", cost: 2, power: 2, tags: ["series5","objective","energy-ramp","winning","marvel-knights","thunderbolts","antiheroes"] },
  { name: "Quake", cost: 2, power: 3, tags: ["series3","on-reveal","tech","shield","wind4"] },
  { name: "Quicksilver", cost: 1, power: 2, tags: ["starter","trigger-card","wiccan","avengers","brotherhood"] },
  { name: "Quicksand", cost: 2, power: 4, tags: ["series4","trigger-card","tech","villains"] },
  { name: "Quinjet", cost: 1, power: 1, tags: ["series3","ongoing","card-generation","arishem-thanos","hand-gen","cost-reduction","shield","wind12"] },
  { name: "Rama-Tut", cost: 4, power: 5, tags: ["series5","on-reveal","wongreveal","random-card-pool","villains"] },
  { name: "Ravonna Renslayer", cost: 2, power: 2, tags: ["series4","ongoing","ongoing-combo","negative","cost-reduction","villains"] },
  { name: "Red Guardian", cost: 3, power: 2, tags: ["series5","on-reveal","afflict","tech","disruption","text-disruption","thunderbolts","antiheroes"] },
  { name: "Red Hulk", cost: 6, power: 10, tags: ["series5","endofturn","scaler","unspent-energy","thunderbolts","monsters","villains","antiheroes"] },
  { name: "Red Shift", cost: 2, power: 3, tags: ["series4","on-reveal","discard","card-generation","random-card-pool","wind18"] },
  { name: "Red Skull", cost: 5, power: 14, tags: ["series3","ongoing","zero-downsides","hydra","villains"] },
  { name: "Redwing", cost: 3, power: 5, tags: ["series5","trigger-card","move","summon","animals"] },
  { name: "Rescue", cost: 4, power: 4, tags: ["series3","on-reveal","self-buff","wind1","wind5"] },
  { name: "Rhino", cost: 2, power: 5, tags: ["series2","on-reveal","no-ability-buff","card-generation","priority-control","board-generator","sinister-six","wind3","spider-verse","animal-themed","villains"] },
  { name: "Rocket and Groot", cost: 3, power: 3, tags: ["series5","moveable","trigger-card","afflict","move","scaler","power-steal","guardians","wind13","wind17","animals"] },
  { name: "Rocket Raccoon", cost: 1, power: 1, tags: ["series1","on-reveal","zoo","bounce","self-buff","guardians","wind2","wind6","geniuses","animals"] },
  { name: "Rockslide", cost: 4, power: 5, tags: ["series3","on-reveal","mill","card-generation","deck-generator","disruption","wind1","wind3","monsters"] },
  { name: "Rogue", cost: 3, power: 3, tags: ["series3","ongoing","on-reveal","ongoing-combo","tech","disruption","text-disruption","xmen","brotherhood"] },
  { name: "Ronan the Accuser", cost: 5, power: 5, tags: ["series3","ongoing","annihilators","wind4","wind16","wind17","villains"] },
  { name: "Sabretooth", cost: 3, power: 5, tags: ["series2","trigger-card","destroy","cost-reduction","revive","brotherhood","wind7","animal-themed","monsters","villains"] },
  { name: "Sage", cost: 3, power: 0, tags: ["series5","on-reveal","wongreveal","bounce","negative","self-buff","hellfire-club","wind6","wind8"] },
  { name: "Sam Wilson Captain America", cost: 2, power: 3, tags: ["series5","on-reveal","move","ongoing-combo","card-generation","mini-movers","aurora","board-generator","scaler","self-buff","unique-card-creation","avengers","wind19"] },
  { name: "Sandman", cost: 5, power: 8, tags: ["series2","on-reveal","tech","disruption","spider-verse","sinister-six","villains"] },
  { name: "Sandstorm", cost: 2, power: 0, tags: ["series4","on-reveal","no-ability-buff","spells","card-generation","give-power","row-interaction"] },
  { name: "Sasquatch", cost: 6, power: 11, tags: ["series4","trigger-card","cost-reduction","play-requirement","wind2","wind7","wind14","animal-themed","monsters"] },
  { name: "Sauron", cost: 1, power: 2, tags: ["series3","on-reveal","zero-downsides","text-disruption","animal-themed","monsters","villains"] },
  { name: "Scarlet Spider", cost: 4, power: 5, tags: ["series5","activate","buff","card-generation","shou-lao","card-copy","board-generator","midnight-sons","wind16","spider-verse","animal-themed"] },
  { name: "Scarlet Witch", cost: 2, power: 3, tags: ["series1","on-reveal","location","avengers","brotherhood","west-coast-avengers","magicians"] },
  { name: "Scorn", cost: 1, power: 2, tags: ["series5","trigger-card","discard","revive","scaler","give-power","symbiotes","wind16"] },
  { name: "Scorpion", cost: 2, power: 3, tags: ["series2","on-reveal","afflict","spider-verse","sinister-six","animal-themed","villains"] },
  { name: "Scorpion Brand New Day", cost: 6, power: 8, tags: ["series5","ongoing","afflict","spider-verse","sinister-six","animal-themed","villains"] },
  { name: "Scream", cost: 2, power: 1, tags: ["series5","trigger-card","afflict","move","scream","scaler","power-steal","symbiotes","wind10","villains"] },
  { name: "Sebastian Shaw", cost: 3, power: 5, tags: ["series4","trigger-card","buff","surfer","scaler","hellfire-club","wind8","wind16","villains"] },
  { name: "Selene", cost: 1, power: 2, tags: ["series3","on-reveal","clog","afflict","hellfire-club","wind13","magicians","villains"] },
  { name: "Selene Horseman of Famine", cost: 4, power: 4, tags: ["series5","objective","afflict","no-ability-buff","self-buff","power-steal","horsemen","magicians","villains"] },
  { name: "Sentinel", cost: 2, power: 3, tags: ["starter","on-reveal","card-generation","hand-gen","card-copy","robots-cyborgs","villains"] },
  { name: "Sentry", cost: 4, power: 9, tags: ["series3","on-reveal","clog","card-generation","werewolf-sentry","zero-downsides","board-generator","unique-card-creation","avengers","thunderbolts","dark-avengers","new-avengers"] },
  { name: "Sera", cost: 5, power: 5, tags: ["series3","ongoing","ongoing-combo","surfer","cost-reduction","wind5"] },
  { name: "Sersi", cost: 5, power: 7, tags: ["series5","on-reveal","transform","random-card-pool","celestial-eternals","wind8"] },
  { name: "Shadowlands Daredevil", cost: 2, power: 3, tags: ["series5","on-reveal","no-ability-buff","card-generation","deck-generator","scaler","defenders","marvel-knights","villains"] },
  { name: "Shadow King", cost: 3, power: 4, tags: ["series3","on-reveal","tech","priority-control","disruption","set-power","villains"] },
  { name: "Shang-Chi", cost: 4, power: 3, tags: ["series2","on-reveal","tech","disruption","destroy","avengers","marvel-knights","heroes-for-hire","agents-of-atlas"] },
  { name: "Shang-Chi, Master of the Rings", cost: 3, power: 5, tags: ["series5","gamestart","card-generation","hand-gen","buff","unique-card-creation","give-power","avengers","marvel-knights","heroes-for-hire","agents-of-atlas"] },
  { name: "Shanna", cost: 3, power: 4, tags: ["series3","on-reveal","zoo","card-generation","board-generator","random-card-pool"] },
  { name: "She-Hulk", cost: 6, power: 10, tags: ["series3","trigger-card","highevo","cost-reduction","unspent-energy","avengers","future-foundation"] },
  { name: "Shocker", cost: 2, power: 4, tags: ["starter","no-ability","no-ability-buff","highevo","spider-verse","sinister-six","villains"] },
  { name: "Shou-Lao the Undying", cost: 5, power: 8, tags: ["series5","on-reveal","buff","shou-lao","board-generator","give-power","play-requirement","animals","monsters"] },
  { name: "Shuri", cost: 4, power: 3, tags: ["series3","on-reveal","buff","wongreveal","nimrod-phoenix","double-power","give-power","wakanda","wind2","wind14","geniuses"] },
  { name: "Silk", cost: 2, power: 5, tags: ["series3","trigger-card","move","mini-movers","agents-of-atlas","wind12","spider-verse","animal-themed"] },
  { name: "Silver Sable", cost: 1, power: 0, tags: ["series5","on-reveal","afflict","zoo","bounce","self-buff","power-steal","spider-verse","animal-themed","antiheroes"] },
  { name: "Silver Samurai", cost: 4, power: 6, tags: ["series3","on-reveal","discard","mill","disruption","villains"] },
  { name: "Silver Surfer", cost: 3, power: 2, tags: ["series3","on-reveal","buff","wongreveal","surfer","multi-location-power","give-power","defenders","annihilators"] },
  { name: "Silver Surfer First Steps", cost: 3, power: 5, tags: ["series4","endofturn","wongreveal","effect-multiplier","winning","text-copy","defenders"] },
  { name: "Skaar", cost: 7, power: 12, tags: ["series4","trigger-card","skaar","cost-reduction"] },
  { name: "Snowguard", cost: 1, power: 2, tags: ["series3","on-reveal","card-generation","hand-gen","tech","effect-multiplier","location","unique-card-creation","animal-themed"] },
  { name: "Sparky", cost: 2, power: 2, tags: ["series5","activate","move","give-power","animals","robots-cyborgs"] },
  { name: "Spectrum", cost: 6, power: 7, tags: ["series0","on-reveal","buff","ongoing-combo","multi-location-power","give-power","avengers"] },
  { name: "Speed", cost: 3, power: 3, tags: ["series5","ongoing","ongoing-combo","wiccan","scaler","young-avengers","wind19"] },
  { name: "Spider-Ham", cost: 1, power: 1, tags: ["series3","activate","mill","transform","disruption","text-disruption","spider-verse","animals"] },
  { name: "Spider-Man Brand New Day", cost: 1, power: 2, tags: ["series5","moveable","trigger-card","move","buff","mini-movers","multi-location-power","give-power","spider-verse","avengers","future-foundation","new-avengers","animal-themed"] },
  { name: "Spider-Man", cost: 2, power: 4, tags: ["series3","on-reveal","move","scream","avengers","future-foundation","new-avengers","wind2","wind8","spider-verse","animal-themed"] },
  { name: "Spider-Man 2099", cost: 4, power: 5, tags: ["series3","moveable","trigger-card","afflict","move","wind3","wind11","spider-verse","animal-themed"] },
  { name: "Spider Sense", cost: 5, power: 0, tags: ["series5","on-reveal","move","buff","cost-reduction","give-power","spider-verse"] },
  { name: "Spider-Man Noir", cost: 4, power: 5, tags: ["series5","on-reveal","buff","summon","set-power","spider-verse","animal-themed"] },
  { name: "Spider-Punk", cost: 3, power: 3, tags: ["series5","moveable","trigger-card","afflict","move","scaler","power-steal","spider-verse","animal-themed"] },
  { name: "Spider-Woman", cost: 5, power: 8, tags: ["series1","on-reveal","afflict","spider-verse","shield","new-avengers","animal-themed"] },
  { name: "Squirrel Girl", cost: 1, power: 2, tags: ["series1","on-reveal","no-ability-buff","zoo","card-generation","board-generator","unique-card-creation","wind17","animal-themed"] },
  { name: "Star-Lord", cost: 2, power: 2, tags: ["starter","on-reveal","self-buff","guardians"] },
  { name: "Star-Lord, Master of the Sun", cost: 5, power: 7, tags: ["series5","on-reveal","energy-ramp","unspent-energy","guardians"] },
  { name: "Starbrand", cost: 3, power: 10, tags: ["series5","ongoing","priority-control","skaar","zero-downsides"] },
  { name: "Stardust", cost: 4, power: 6, tags: ["series5","ongoing","tech","villains"] },
  { name: "Starhawk", cost: 2, power: 3, tags: ["series4","on-reveal","buff","give-power"] },
  { name: "Stature", cost: 5, power: 7, tags: ["series3","trigger-card","discard","cost-reduction","young-avengers","wind9"] },
  { name: "Stegron", cost: 4, power: 7, tags: ["series3","on-reveal","move","scream","disruption","animal-themed","monsters","villains"] },
  { name: "Stick", cost: 4, power: 3, tags: ["series4","on-reveal","buff","give-power"] },
  { name: "Storm", cost: 3, power: 1, tags: ["series2","on-reveal","tech","lockdown","location","disruption","xmen","wind10"] },
  { name: "Storm Horseman of Famine", cost: 3, power: 1, tags: ["series5","objective","buff","surfer","give-power","unspent-energy","xmen","horsemen","villains"] },
  { name: "Strange Supreme", cost: 2, power: 2, tags: ["series5","endofturn","merge","arishem-thanos","scaler","magicians"] },
  { name: "Strong Guy", cost: 3, power: 3, tags: ["series1","ongoing"] },
  { name: "Stryfe", cost: 4, power: 6, tags: ["series5","objective","wongreveal","effect-multiplier","villains"] },
  { name: "Sub-Mariner", cost: 1, power: 2, tags: ["series5","trigger-card","zoo","buff","card-generation","random-card-pool","defenders","illuminati","cabal","atlanteans"] },
  { name: "Sunspot", cost: 1, power: 0, tags: ["series2","endofturn","highevo","end-of-turn-combo","scaler","unspent-energy","hellfire-club","new-mutants","x-force"] },
  { name: "Super-Adaptoid", cost: 3, power: 5, tags: ["series4","on-reveal","tech","text-disruption","villains"] },
  { name: "Super-Skrull", cost: 4, power: 2, tags: ["series3","ongoing","ongoing-combo","tech","effect-multiplier","wind4","villains"] },
  { name: "Supergiant", cost: 4, power: 5, tags: ["series4","on-reveal","tech","priority-control","delayed-reveal","black-order","villains"] },
  { name: "Superior Spider-Man", cost: 3, power: 4, tags: ["series5","startofturn","buff","zombie-galacti","energy-ramp","wind19","spider-verse","animal-themed","villains"] },
  { name: "Surge", cost: 2, power: 1, tags: ["series5","on-reveal","buff","cost-reduction","give-power"] },
  { name: "Surtur", cost: 3, power: 5, tags: ["series5","trigger-card","skaar","scaler","wind14","wind17","monsters","villains"] },
  { name: "Swarm", cost: 2, power: 3, tags: ["series2","trigger-card","discard","card-generation","hand-gen","card-copy","cost-reduction","sinister-six","wind9","animal-themed","villains"] },
  { name: "Sword Master", cost: 3, power: 7, tags: ["series1","on-reveal","discard","agents-of-atlas","wind13"] },
  { name: "Symbiote Spider-Man", cost: 4, power: 7, tags: ["series5","activate","merge","buff","wongreveal","nimrod-phoenix","effect-multiplier","text-copy","symbiotes","avengers","future-foundation","new-avengers","wind14","spider-verse","animal-themed"] },
  { name: "Tarantula", cost: 2, power: 2, tags: ["series5","endofturn","priority-control","scaler","give-power","spider-verse","heroes-for-hire","animal-themed"] },
  { name: "Taskmaster", cost: 6, power: 0, tags: ["series3","on-reveal","negative","set-power","shield","thunderbolts","villains"] },
  { name: "Techno-Organic Virus", cost: 2, power: 0, tags: ["series5","on-reveal","card-generation","zero-downsides","card-copy","multi-location-power","hand-gen","spells","priority-control","text-disruption","villains"] },
  { name: "Terrax the Tamer", cost: 3, power: 4, tags: ["series4","on-reveal","card-generation","deck-generator","winning","villains"] },
  { name: "Thaddeus Ross", cost: 2, power: 2, tags: ["series5","endofturn","draw","unspent-energy"] },
  { name: "Thanos", cost: 6, power: 12, tags: ["series5","gamestart","zoo","card-generation","arishem-thanos","location","cost-reduction","deck-generator","draw","unique-card-creation","black-order","celestial-eternals","villains"] },
  { name: "The Ancient One", cost: 3, power: 5, tags: ["series5","on-reveal","card-generation","hand-gen","ongoing-combo","effect-multiplier","spells","unique-card-creation","text-copy","magicians"] },
  { name: "The Collector", cost: 2, power: 2, tags: ["series2","trigger-card","card-generation","hand-gen","scaler"] },
  { name: "The Fallen One", cost: 5, power: 5, tags: ["series5","on-reveal","buff","energy-ramp","villains"] },
  { name: "The First Ghost Rider", cost: 2, power: 7, tags: ["series4","on-reveal","discard"] },
  { name: "The Hood", cost: 1, power: -3, tags: ["series3","on-reveal","clog","card-generation","hand-gen","no-ability-buff","werewolf-sentry","unique-card-creation","cabal","villains"] },
  { name: "The Hunger", cost: 1, power: 0, tags: ["series4","on-reveal","zombie","spells","card-generation","board-generator","give-power","monsters"] },
  { name: "The Infinaut", cost: 6, power: 20, tags: ["series2","trigger-card","highevo","play-requirement","zero-downsides","wind2","monsters"] },
  { name: "The Living Tribunal", cost: 6, power: 9, tags: ["series4","ongoing","ongoing-combo","multi-location-power","cosmic-entities"] },
  { name: "The Thing", cost: 4, power: 7, tags: ["starter","no-ability","afflict","no-ability-buff","highevo","fantastic4","future-foundation","monsters"] },
  { name: "The Thing First Steps", cost: 5, power: 6, tags: ["series5","endofturn","destroy","end-of-turn-combo","aurora","scaler","disruption","full-location","fantastic4","future-foundation"] },
  { name: "Thena", cost: 2, power: 0, tags: ["series5","endofturn","end-of-turn-combo","scaler","play-requirement","celestial-eternals","wind6"] },
  { name: "Thor", cost: 3, power: 5, tags: ["series3","on-reveal","card-generation","hammer-bros","deck-generator","self-buff","unique-card-creation","avengers","asgardians","wind13","wind19"] },
  { name: "Titania", cost: 1, power: 5, tags: ["series3","trigger-card","clog","zero-downsides","wind2","wind15","villains"] },
  { name: "Tombstone", cost: 2, power: 4, tags: ["series4","on-reveal","destroy","spider-verse","villains"] },
  { name: "Topaz", cost: 2, power: 4, tags: ["series4","trigger-card","move"] },
  { name: "Toxie Doxie", cost: 2, power: 3, tags: ["series4","on-reveal","buff","give-power","wind18","villains"] },
  { name: "Toxin", cost: 2, power: 2, tags: ["series5","on-reveal","bounce","self-buff","symbiotes"] },
  { name: "Triton", cost: 3, power: 6, tags: ["series4","on-reveal","buff","give-power","animal-themed"] },
  { name: "Typhoid Mary", cost: 4, power: 10, tags: ["series3","ongoing","zero-downsides","afflict","skaar","wind6","wind13","wind14","wind15","villains"] },
  { name: "U.S. Agent", cost: 2, power: 3, tags: ["series5","ongoing","afflict","west-coast-avengers","wind3","wind6","wind9","antiheroes"] },
  { name: "Uatu the Watcher", cost: 1, power: 2, tags: ["series1","gamestart","cosmic-entities"] },
  { name: "Ultron", cost: 6, power: 8, tags: ["series3","on-reveal","no-ability-buff","zoo","card-generation","board-generator","unique-card-creation","wind1","wind12","wind14","robots-cyborgs","villains"] },
  { name: "Uncle Ben", cost: 1, power: 2, tags: ["series4","trigger-card","destroy","card-generation","board-generator","spider-verse"] },
  { name: "Valentina", cost: 2, power: 3, tags: ["series4","on-reveal","afflict","card-generation","hand-gen","cost-reduction","random-card-pool","thunderbolts","villains"] },
  { name: "Valkyrie", cost: 5, power: 3, tags: ["series3","on-reveal","tech","disruption","set-power","asgardians","defenders"] },
  { name: "Venus", cost: 3, power: 3, tags: ["series5","trigger-card","buff","effect-multiplier","give-power","agents-of-atlas"] },
  { name: "Venom", cost: 3, power: 3, tags: ["series3","on-reveal","destroy","nimrod-phoenix","self-buff","symbiotes","wind12","spider-verse","antiheroes"] },
  { name: "Victoria Hand", cost: 2, power: 2, tags: ["series5","ongoing","card-generation","hand-gen","multi-location-power","wind15"] },
  { name: "Viper", cost: 3, power: 4, tags: ["series3","on-reveal","clog","disruption","hydra","animal-themed","villains"] },
  { name: "Vision", cost: 5, power: 9, tags: ["series2","moveable","move","avengers","west-coast-avengers","robots-cyborgs"] },
  { name: "Viv Vision", cost: 3, power: 4, tags: ["series5","startofturn","buff","priority-control","surfer","winning","give-power","robots-cyborgs"] },
  { name: "Vulture", cost: 1, power: 3, tags: ["series2","trigger-card","move","scaler","spider-verse","sinister-six","animal-themed","villains"] },
  { name: "Wade Wilson", cost: 2, power: 2, tags: ["series4","trigger-card","destroy","summon","give-power","thunderbolts","x-force"] },
  { name: "War Machine", cost: 5, power: 9, tags: ["series5","ongoing","lockdown","zero-downsides","avengers","west-coast-avengers"] },
  { name: "Warlock", cost: 3, power: 4, tags: ["series5","activate","cost-reduction","unspent-energy","new-mutants"] },
  { name: "Warpath", cost: 4, power: 5, tags: ["series2","ongoing","ongoing-combo","x-force"] },
  { name: "Wasp", cost: 0, power: 1, tags: ["series3","no-ability","afflict","no-ability-buff","highevo","avengers","west-coast-avengers","animal-themed"] },
  { name: "Wave", cost: 3, power: 6, tags: ["series3","on-reveal","cost-reduction","agents-of-atlas","wind16"] },
  { name: "Weapon H", cost: 7, power: 14, tags: ["series5","trigger-card","discard","cost-reduction","revive","monsters","antiheroes"] },
  { name: "Weapon X Wolverine", cost: 2, power: 3, tags: ["series5","trigger-card","destroy","scaler","xmen","new-avengers","x-force","animal-themed"] },
  { name: "Web Sling", cost: 1, power: 0, tags: ["series4","on-reveal","move","give-power","wind19","spells"] },
  { name: "Werewolf By Night", cost: 3, power: 3, tags: ["series4","trigger-card","werewolf-sentry","bounce","scaler","monsters"] },
  { name: "White Queen", cost: 3, power: 5, tags: ["series1","on-reveal","card-generation","hand-gen","card-copy","xmen","hellfire-club","cabal"] },
  { name: "White Tiger", cost: 5, power: 1, tags: ["series0","on-reveal","no-ability-buff","wongreveal","card-generation","board-generator","unique-card-creation","heroes-for-hire","wind1","animal-themed"] },
  { name: "White Widow", cost: 2, power: 2, tags: ["series5","on-reveal","clog","card-generation","board-generator","disruption","unique-card-creation","full-location","thunderbolts","animal-themed"] },
  { name: "Wiccan", cost: 4, power: 6, tags: ["series5","on-reveal","wiccan","energy-ramp","young-avengers","magicians"] },
  { name: "Wild Child", cost: 2, power: 1, tags: ["series4","ongoing","discard","destroy","fantomex","animal-themed","monsters","villains"] },
  { name: "Wilson Fisk", cost: 5, power: 9, tags: ["series5","trigger-card","priority-control","cost-reduction","spider-verse","villains"] },
  { name: "Wolfsbane", cost: 3, power: 1, tags: ["series0","on-reveal","wongreveal","self-buff","new-mutants","wind1","animal-themed","monsters"] },
  { name: "Wolverine", cost: 2, power: 3, tags: ["series1","trigger-card","discard","destroy","summon","xmen","midnight-sons","new-avengers","x-force","wind10","animal-themed"] },
  { name: "Wolverine Horseman of War", cost: 4, power: 3, tags: ["series5","objective","buff","multi-location-power","give-power","xmen","horsemen","new-avengers","x-force","animal-themed"] },
  { name: "Wong", cost: 4, power: 2, tags: ["series3","ongoing","wongreveal","effect-multiplier","midnight-sons","magicians"] },
  { name: "X-23", cost: 1, power: 1, tags: ["series4","trigger-card","energy-ramp","summon","discard","destroy","xmen","x-force","wind12"] },
  { name: "Xorn", cost: 2, power: 3, tags: ["series5","trigger-card","move","scream"] },
  { name: "Yellowjacket", cost: 0, power: 2, tags: ["series3","on-reveal","zero-downsides","afflict","animal-themed","villains"] },
  { name: "Yondu", cost: 1, power: 2, tags: ["series1","on-reveal","mill","guardians","wind11"] },
  { name: "Zabu", cost: 1, power: 1, tags: ["series3","on-reveal","cost-reduction","animals"] },
  { name: "Zero", cost: 1, power: 3, tags: ["series3","on-reveal","zero-downsides","text-disruption","wind2","wind15","villains"] },
  { name: "Zombie Captain Marvel", cost: 4, power: 5, tags: ["series5","activate","destroy","move","zombie","self-buff","winning","avengers","monsters","villains"] },
  { name: "Zombie Galacti", cost: 7, power: 5, tags: ["series5","gamestart","zombie","zombie-galacti","card-copy","transform","deck-generator","wind18","monsters","villains"] },
  { name: "Zombie Giant-Man", cost: 5, power: 4, tags: ["series4","on-reveal","zombie","card-generation","board-generator","give-power","self-buff","avengers","monsters","villains"] },
  { name: "Zombie Mister Fantastic", cost: 2, power: 2, tags: ["series5","on-reveal","activate","zombie","card-generation","aurora","board-generator","give-power","fantastic4","future-foundation","illuminati","wind19","geniuses","monsters","villains"] },
  { name: "Zombie Power Man", cost: 2, power: 4, tags: ["series4","endofturn","zombie","winning","defenders","marvel-knights","heroes-for-hire","thunderbolts","new-avengers","monsters","villains"] },
  { name: "Zombie Scarlet Witch", cost: 3, power: 4, tags: ["series5","trigger-card","zombie","card-generation","board-generator","give-power","avengers","brotherhood","west-coast-avengers","magicians","monsters","villains"] },
  { name: "Zombie Sentry", cost: 2, power: 1, tags: ["series4","on-reveal","zombie","card-generation","board-generator","give-power","avengers","thunderbolts","dark-avengers","new-avengers","monsters","villains"] },
  { name: "Sinister Six", cost: 6, power: 12, tags: ["series5","gamestart","merge","summon","sinister-six","spider-verse","villains"] }
];

const cards = cardDatabase.map(c => c.name);
