const players = [
  "Dejwid",
  "Dawid ak. Void",
  "Budiso",
  "Pluton",
  "Raciatek",
  "Supcio",
  "Weregesu",
  "Matixmgg",
  "Fizjoradek",
  "Kmythic",
  "Maniek",
];

const matches = [
  { p1: "Dejwid", p2: "Maniek", pts1: 22, pts2: 3 },
  { p1: "Dejwid", p2: "Dawid ak. Void", pts1: 6, pts2: 19 },
  { p1: "Dawid ak. Void", p2: "Budiso", pts1: 24, pts2: 1 },
  { p1: "Raciatek", p2: "Budiso", pts1: 18, pts2: 7 },
  { p1: "Dawid ak. Void", p2: "Maniek", pts1: 21, pts2: 4 },
  { p1: "Raciatek", p2: "Fizjoradek", pts1: 21, pts2: 4 },
  { p1: "Kmythic", p2: "Weregesu", pts1: 25, pts2: 0 },
  { p1: "Fizjoradek", p2: "Maniek", pts1: 17, pts2: 8 },
  { p1: "Weregesu", p2: "Maniek", pts1: 24, pts2: 1 },
  { p1: "Fizjoradek", p2: "Dawid ak. Void", pts1: 21, pts2: 4 },
  { p1: "Kmythic", p2: "Maniek", pts1: 23, pts2: 2 },
  { p1: "Weregesu", p2: "Raciatek", pts1: 21, pts2: 4 },
  { p1: "Kmythic", p2: "Dawid ak. Void", pts1: 21, pts2: 4 },
  { p1: "Fizjoradek", p2: "Kmythic", pts1: 21, pts2: 4 },
  { p1: "Fizjoradek", p2: "Weregesu", pts1: 22, pts2: 3 },
];
