const cardDatabase = [
  { name: "Abomination", cost: 5, power: 9, tags: ["wind10"] },
  { name: "Absorbing Man", cost: 4, power: 5, tags: ["wind11"] },
  { name: "Adam Warlock", cost: 2, power: 0, tags: ["wind12"] },
  { name: "Adamantium Infusion", cost: 4, power: 0, tags: [] },
  { name: "Agamotto", cost: 5, power: 10, tags: [] },
  { name: "Agatha Harkness", cost: 6, power: 12, tags: ["wind18"] },
  { name: "Agony", cost: 1, power: 3, tags: [] },
  { name: "Air-Walker", cost: 3, power: 4, tags: [] },
  { name: "Aero", cost: 5, power: 9, tags: [] },
  { name: "Ajax", cost: 5, power: 7, tags: [] },
  { name: "Agent 13", cost: 1, power: 2, tags: [] },
  { name: "Agent Coulson", cost: 3, power: 4, tags: ["wind9"] },
  { name: "Agent Venom", cost: 2, power: 5, tags: [] },
  { name: "America Chavez", cost: 1, power: 2, tags: ["wind9"] },
  { name: "Ancient One", cost: 3, power: 5, tags: [] },
  { name: "Angel", cost: 2, power: 3, tags: ["wind3"] },
  { name: "Angela", cost: 2, power: 3, tags: ["wind2"] },
  { name: "Annihilus", cost: 5, power: 8, tags: [] },
  { name: "Ant-Man", cost: 1, power: 1, tags: ["wind4","avengers"] },
  { name: "Anti-Venom", cost: 4, power: 7, tags: ["wind12"] },
  { name: "Apocalypse", cost: 6, power: 8, tags: ["wind18"] },
  { name: "Alioth", cost: 6, power: 7, tags: [] },
  { name: "Araña", cost: 1, power: 2, tags: [] },
  { name: "Arishem", cost: 7, power: 7, tags: ["wind6","wind10"] },
  { name: "Arnim Zola", cost: 6, power: 0, tags: [] },
  { name: "Armor", cost: 2, power: 3, tags: ["wind1","wind8"] },
  { name: "Ares", cost: 4, power: 6, tags: [] },
  { name: "Astral Projection", cost: 3, power: 0, tags: [] },
  { name: "Attuma", cost: 4, power: 10, tags: ["wind3"] },
  { name: "Aurora", cost: 6, power: 6, tags: ["wind19"] },
  { name: "Awesome Andy", cost: 2, power: 2, tags: [] },
  { name: "Baron Mordo", cost: 2, power: 3, tags: ["wind15"] },
  { name: "Baron Zemo", cost: 3, power: 5, tags: ["wind16"] },
  { name: "Bast", cost: 1, power: 1, tags: [] },
  { name: "Bastion", cost: 4, power: 3, tags: [] },
  { name: "Batroc the Leaper", cost: 1, power: 2, tags: [] },
  { name: "Beast", cost: 3, power: 5, tags: ["wind11","wind17"] },
  { name: "Beta Ray Bill", cost: 4, power: 6, tags: ["wind4"] },
  { name: "Bishop", cost: 3, power: 2, tags: [] },
  { name: "Black Bolt", cost: 5, power: 7, tags: ["wind1"] },
  { name: "Black Cat", cost: 1, power: 4, tags: [] },
  { name: "Black Knight", cost: 1, power: 2, tags: [] },
  { name: "Black Panther", cost: 5, power: 5, tags: ["wind13"] },
  { name: "Black Swann", cost: 2, power: 3, tags: [] },
  { name: "Black Widow", cost: 3, power: 3, tags: ["wind5","avengers"] },
  { name: "Blade", cost: 1, power: 3, tags: [] },
  { name: "Blink", cost: 5, power: 8, tags: ["wind10"] },
  { name: "Blob", cost: 6, power: 0, tags: [] },
  { name: "Blue Marvel", cost: 5, power: 3, tags: ["wind12"] },
  { name: "Brood", cost: 3, power: 2, tags: [] },  
  { name: "Bruce Banner", cost: 2, power: 1, tags: [] },
  { name: "Bucky Barnes", cost: 2, power: 1, tags: ["wind14"] },
  { name: "Bullseye", cost: 3, power: 2, tags: [] },
  { name: "Cable", cost: 2, power: 4, tags: ["wind8","wind15"] },
  { name: "Caliban Horseman of Pestilence", cost: 3, power: 4, tags: [] },
  { name: "Caiera", cost: 3, power: 4, tags: [] },
  { name: "Cannonball", cost: 5, power: 6, tags: ["wind3"] },
  { name: "Captain America", cost: 3, power: 3, tags: ["avengers"] },
  { name: "Captain Carter", cost: 3, power: 2, tags: [] },
  { name: "Captain Marvel", cost: 4, power: 5, tags: [] },
  { name: "Carnage", cost: 2, power: 2, tags: [] },
  { name: "Cassandra Nova", cost: 3, power: 0, tags: ["wind14"] },
  { name: "Cerebro", cost: 3, power: 0, tags: [] },
  { name: "Chamber", cost: 2, power: 2, tags: [] },
  { name: "Chameleon", cost: 3, power: 3, tags: [] },
  { name: "Clea", cost: 1, power: 3, tags: [] },
  { name: "Cloak", cost: 2, power: 4, tags: ["wind3"] },
  { name: "Cobra", cost: 2, power: 3, tags: [] },
  { name: "Colleen Wing", cost: 2, power: 3, tags: [] },
  { name: "Colonel America", cost: 3, power: 4, tags: [] },
  { name: "Colossus", cost: 2, power: 4, tags: [] },
  { name: "Copycat", cost: 3, power: 5, tags: ["wind9","wind11"] },
  { name: "Corvus Glaive", cost: 3, power: 5, tags: [] },
  { name: "Cosmic Ghost Rider", cost: 5, power: 6, tags: [] },
  { name: "Cosmo", cost: 3, power: 3, tags: ["wind5","animal"] },
  { name: "Crossbones", cost: 4, power: 10, tags: ["wind10"] },
  { name: "Crystal", cost: 3, power: 4, tags: [] },
  { name: "Cull Obsidian", cost: 4, power: 10, tags: ["wind2","wind9"] },
  { name: "Cyclops", cost: 3, power: 5, tags: ["wind4"] },
  { name: "Dagger", cost: 2, power: 2, tags: ["wind7"] },
  { name: "Daken", cost: 3, power: 4, tags: [] },
  { name: "Danger", cost: 4, power: 6, tags: [] },
  { name: "Daredevil", cost: 2, power: 3, tags: [] },  
  { name: "Darkhawk", cost: 5, power: 3, tags: ["wind18"] },
  { name: "Dazzler", cost: 2, power: 2, tags: ["wind5"] },
  { name: "Deadpool", cost: 1, power: 1, tags: ["wind2","wind8"] },
  { name: "Deafening Chord", cost: 1, power: 0, tags: [] },
  { name: "Death", cost: 8, power: 12, tags: ["wind17"] },
  { name: "Deathlok", cost: 3, power: 5, tags: [] },
  { name: "Debrii", cost: 3, power: 7, tags: [] },
  { name: "Destroyer", cost: 6, power: 18, tags: ["wind1"] },
  { name: "Devil Dinosaur", cost: 5, power: 4, tags: [] },
  { name: "Diamondback", cost: 3, power: 3, tags: [] },
  { name: "Doctor Doom", cost: 6, power: 5, tags: ["wind15","wind17"] },
  { name: "Doctor Doom 2099", cost: 4, power: 6, tags: [] },
  { name: "Doctor Octopus", cost: 4, power: 8, tags: ["wind8","wind17"] },
  { name: "Doctor Strange", cost: 2, power: 4, tags: ["wind11","wind17"] },
  { name: "Domino", cost: 2, power: 4, tags: [] },
  { name: "Dormammu", cost: 7, power: 13, tags: [] },
  { name: "Dracula", cost: 4, power: 1, tags: [] },
  { name: "Dragon Lord", cost: 5, power: 5, tags: [] },
  { name: "Dragon of the Moon", cost: 3, power: 4, tags: [] },
  { name: "Drax", cost: 4, power: 5, tags: ["wind16"] },
  { name: "Drax Avatar of Life", cost: 3, power: 4, tags: [] },
  { name: "Ebony Maw", cost: 1, power: 7, tags: ["wind16"] },
  { name: "Echo", cost: 1, power: 2, tags: [] },
  { name: "Electro", cost: 3, power: 5, tags: [] },
  { name: "Elektra", cost: 1, power: 2, tags: ["wind1"] },
  { name: "Elixir", cost: 2, power: 3, tags: [] },
  { name: "Elsa Bloodstone", cost: 3, power: 5, tags: ["wind6"] },
  { name: "Emperor Hulkling", cost: 6, power: 12, tags: [] },
  { name: "Enchantress", cost: 5, power: 8, tags: [] },
  { name: "En Sbah Nur", cost: 4, power: 5, tags: [] },
  { name: "Esme Cuckoo", cost: 3, power: 4, tags: [] },
  { name: "Eson", cost: 6, power: 10, tags: [] },
  { name: "Ezekiel Sims", cost: 2, power: 2, tags: [] },
  { name: "Falcon", cost: 2, power: 3, tags: ["avengers"] },  
  { name: "Fan Fei", cost: 4, power: 5, tags: [] },
  { name: "Fantasticar", cost: 4, power: 5, tags: [] },
  { name: "Fantomex", cost: 4, power: 7, tags: [] },
  { name: "Fastball Special", cost: 2, power: 0, tags: [] },
  { name: "Fenris Wolf", cost: 3, power: 4, tags: [] },
  { name: "Fin Fang Foom", cost: 7, power: 10, tags: [] },
  { name: "Firehair", cost: 2, power: 3, tags: [] },
  { name: "Firelord", cost: 4, power: 7, tags: [] },
  { name: "Forge", cost: 2, power: 2, tags: ["wind13","wind18"] },
  { name: "Frigga", cost: 3, power: 4, tags: [] },
  { name: "Galacta", cost: 4, power: 6, tags: [] },
  { name: "Galactus", cost: 6, power: 6, tags: [] },
  { name: "Galactus First Steps", cost: 6, power: 12, tags: [] },
  { name: "Gambit", cost: 3, power: 3, tags: [] },
  { name: "Gambit Horseman of Death", cost: 3, power: 3, tags: [] },
  { name: "Gamora", cost: 5, power: 8, tags: ["wind9","wind13"] },
  { name: "Ghost", cost: 3, power: 4, tags: [] },
  { name: "Ghost Rider", cost: 4, power: 5, tags: ["wind18"] },
  { name: "Ghost-Spider", cost: 1, power: 3, tags: ["wind11"] },
  { name: "Giganto", cost: 6, power: 16, tags: [] },
  { name: "Gilgamesh", cost: 5, power: 9, tags: ["wind19"] },
  { name: "Gladiator", cost: 3, power: 8, tags: [] },
  { name: "Goliath", cost: 2, power: 1, tags: [] },
  { name: "Goose", cost: 2, power: 2, tags: ["wind2","animal"] },
  { name: "Gorgon", cost: 2, power: 3, tags: [] },
  { name: "Gorr", cost: 6, power: -1, tags: [] },
  { name: "Grand Master", cost: 2, power: 3, tags: ["wind1"] },
  { name: "Green Goblin", cost: 3, power: -3, tags: [] },
  { name: "Groot", cost: 3, power: 4, tags: ["wind5","wind17"] },
  { name: "Gwenpool", cost: 4, power: 5, tags: [] },
  { name: "H.E.R.B.I.E.", cost:2, power: 3, tags: [] },
  { name: "Havok", cost: 2, power: 1, tags: [] },
  { name: "Hawkeye Kate Bishop", cost: 2, power: 3, tags: [] },
  { name: "Hawkeye", cost: 1, power: 1, tags: ["avengers"] },
  { name: "Hazmat", cost: 3, power: 3, tags: [] },
  { name: "Headpool", cost: 1, power: 1, tags: [] },
  { name: "Heimdall", cost: 6, power: 10, tags: ["wind16"] },
  { name: "Hela", cost: 6, power: 6, tags: [] },
  { name: "Helicarrier", cost: 6, power: 10, tags: [] },
  { name: "Hellcow", cost: 4, power: 6, tags: ["wind6","wind11"] },
  { name: "Hellion", cost: 5, power: 8, tags: [] },
  { name: "Hercules", cost: 3, power: 5, tags: ["wind6"] },
  { name: "High Evolutionary", cost: 4, power: 7, tags: [] },
  { name: "Hit-Monkey", cost: 3, power: 3, tags: ["wind3","wind19"] },
  { name: "Hobgoblin", cost: 5, power: -8, tags: [] },
  { name: "Hope Summers", cost: 3, power: 4, tags: [] },
  { name: "Howard the Duck", cost: 1, power: 2, tags: [] },
  { name: "Hulk", cost: 6, power: 14, tags: ["wind3","avengers"] },
  { name: "Hulkbuster", cost: 2, power: 3, tags: ["wind13"] },
  { name: "Human Torch", cost: 3, power: 2, tags: [] },
  { name: "Human Torch First Steps", cost: 3, power: 2, tags: [] },
  { name: "Hydra Bob", cost: 1, power: 4, tags: ["wind8"] },
  { name: "Hydra Stomper", cost: 3, power: 3, tags: [] },
  { name: "Hydro-Man", cost: 5, power: 8, tags: [] },
  { name: "Iceman", cost: 1, power: 2, tags: [] },
  { name: "Infinity Ultron", cost: 5, power: 6, tags: [] },
  { name: "Invisible Woman", cost: 2, power: 4, tags: [] },
  { name: "Invisible Woman First Steps", cost: 3, power: 3, tags: [] },
  { name: "Iron Fist", cost: 1, power: 3, tags: ["wind3","wind12"] },
  { name: "Iron Lad", cost: 4, power: 7, tags: ["wind7"] },
  { name: "Iron Man", cost: 5, power: 0, tags: ["wind7","avengers"] },
  { name: "Iron Patriot", cost: 2, power: 3, tags: [] },
  { name: "Ironheart", cost: 3, power: 0, tags: ["wind11"] },
  { name: "Isca the Unbeaten", cost: 4, power: 3, tags: [] },
  { name: "Jane Foster Mighty Thor", cost: 5, power: 9, tags: ["wind4"] },
  { name: "Jack Flag", cost: 3, power: 3, tags: [] },
  { name: "Jean Grey", cost: 3, power: 4, tags: ["wind15"] },
  { name: "Jeff the Baby Land Shark", cost: 2, power: 4, tags: ["wind9","animal"] },
  { name: "Jennifer Kale", cost: 2, power: 3, tags: ["wind18"] },
  { name: "Jessica Jones", cost: 4, power: 5, tags: [] },
  { name: "Jim Hammond Human Torch", cost: 1, power: 2, tags: [] },
  { name: "Joaquin Torres Falcon II", cost: 2, power: 3, tags: [] },
  { name: "Jocasta", cost: 3, power: 3, tags: [] },
  { name: "Jubilee", cost: 4, power: 1, tags: [] },
  { name: "Juggernaut", cost: 4, power: 5, tags: [] },
  { name: "Juggernaut Horseman of War", cost: 2, power: 2, tags: [] },
  { name: "Ka-Zar", cost: 4, power: 5, tags: [] },
  { name: "Kahhori", cost: 4, power: 6, tags: [] },
  { name: "Kang", cost: 3, power: 4, tags: [] },
  { name: "Khonshu", cost: 6, power: 5, tags: [] },  
  { name: "Kid Omega", cost: 2, power: 1, tags: [] },
  { name: "Killmonger", cost: 3, power: 3, tags: [] },
  { name: "King Eitri", cost: 1, power: 3, tags: [] },
  { name: "Kingpin", cost: 1, power: 3, tags: ["wind5","wind10"] },
  { name: "Kitty Pryde", cost: 1, power: 1, tags: ["wind3"] },
  { name: "Klaw", cost: 5, power: 4, tags: [] },
  { name: "Knull", cost: 6, power: 0, tags: ["wind17"] },
  { name: "Korg", cost: 1, power: 2, tags: ["wind8","wind10","wind13"] },
  { name: "Kraglin", cost: 3, power: 3, tags: ["wind18"] },
  { name: "Kraven", cost: 2, power: 3, tags: ["wind5","wind10"] },
  { name: "Lady Deathstrike", cost: 5, power: 7, tags: ["wind14"] },
  { name: "Lady Sif", cost: 3, power: 5, tags: [] },
  { name: "Lasher", cost: 2, power: 2, tags: ["wind16"] },
  { name: "Laufey", cost: 4, power: 5, tags: [] },
  { name: "Leader", cost: 6, power: 5, tags: ["wind7"] },
  { name: "Leech", cost: 4, power: 4, tags: [] },
  { name: "Legion", cost: 5, power: 7, tags: ["wind8"] },
  { name: "Lin Lie Iron Fist", cost: 2, power: 3, tags: [] },
  { name: "Lizard", cost: 2, power: 6, tags: [] },
  { name: "Lockheed", cost: 2, power: 1, tags: [] },
  { name: "Lockjaw", cost: 2, power: 3, tags: [] },
  { name: "Loki", cost: 1, power: 2, tags: [] },
  { name: "Luke Cage", cost: 3, power: 2, tags: ["wind5"] },
  { name: "Luna Snow", cost: 3, power: 3, tags: [] },
  { name: "M'baku", cost: 1, power: 3, tags: [] },
  { name: "M.O.D.O.K.", cost: 5, power: 7, tags: ["wind18"] },
  { name: "Mad Thinker", cost: 1, power: 2, tags: [] },
  { name: "Madame Web", cost: 2, power: 1, tags: [] },
  { name: "Magik", cost: 3, power: 2, tags: ["wind10"] },
  { name: "Magneto", cost: 6, power: 12, tags: [] },
  { name: "Magus", cost: 2, power: 3, tags: [] },
  { name: "Majestic Wingbeat", cost: 1, power: 0, tags: [] },  
  { name: "Major Victory", cost: 3, power: 4, tags: [] },
  { name: "Makkari", cost: 3, power: 3, tags: [] },
  { name: "Malekith", cost: 4, power: 6, tags: [] },
  { name: "Man-Spider", cost: 5, power: 1, tags: [] },
  { name: "Man-Thing", cost: 4, power: 7, tags: ["wind13","wind15"] },
  { name: "Mantis", cost: 1, power: 3, tags: ["wind9"] },
  { name: "Maria Hill", cost: 1, power: 2, tags: ["wind19"] },
  { name: "Marrow", cost: 2, power: 3, tags: [] },
  { name: "Martyr", cost: 1, power: 5, tags: [] },
  { name: "Marvel Boy", cost: 3, power: 2, tags: [] },
  { name: "Master Mold", cost: 2, power: 3, tags: [] },
  { name: "Maverick", cost: 3, power: 2, tags: [] },
  { name: "Maximus", cost: 2, power: 6, tags: ["wind4","wind13","wind15","wind16"] },
  { name: "Medusa", cost: 2, power: 2, tags: [] },
  { name: "Mercury", cost: 3, power: 4, tags: [] },
  { name: "Merlin", cost: 2, power: 2, tags: [] },
  { name: "Miek", cost: 1, power: 1, tags: [] },
  { name: "Miles Morales Spider-Man", cost: 4, power: 6, tags: ["wind12","wind19"] },
  { name: "Mirage", cost: 2, power: 3, tags: ["wind15"] },
  { name: "Misery", cost: 4, power: 8, tags: [] },
  { name: "Mister Fantastic", cost: 3, power: 1, tags: [] },
  { name: "Mister Fantastic First Steps", cost: 3, power: 4, tags: ["wind19"] },
  { name: "Mister Negative", cost: 4, power: -1, tags: ["wind18"] },
  { name: "Mister Sinister", cost: 2, power: 2, tags: ["wind14"] },
  { name: "Misty Knight", cost: 1, power: 3, tags: [] },
  { name: "Mobius M. Mobius", cost: 3, power: 3, tags: [] },
  { name: "Mockingbird", cost: 6, power: 9, tags: [] },
  { name: "Moira X", cost: 1, power: 2, tags: [] },
  { name: "Mojo", cost: 2, power: 2, tags: ["wind9","wind12"] },
  { name: "Mole Man", cost: 3, power: 4, tags: [] },
  { name: "Moon Girl", cost: 4, power: 5, tags: [] },
  { name: "Moon Knight", cost: 3, power: 3, tags: ["wind9"] },
  { name: "Moondragon", cost: 2, power: 2, tags: [] },
  { name: "Moonstone", cost: 4, power: 6, tags: [] },
  { name: "Morbius", cost: 2, power: 0, tags: [] },
  { name: "Morgan le Fay", cost: 3, power: 4, tags: [] },
  { name: "Morph", cost: 3, power: 0, tags: ["wind7","wind10"] },
  { name: "Ms. Marvel", cost: 4, power: 5, tags: ["wind4","wind7"] },
  { name: "Multiple Man", cost: 2, power: 4, tags: ["wind2","wind5","wind11"] },
  { name: "Mysterio", cost: 2, power: 4, tags: ["wind1"] },
  { name: "Mystique", cost: 3, power: 0, tags: ["wind4"] },
  { name: "Nakia", cost: 3, power: 4, tags: [] },
  { name: "Namor", cost: 4, power: 6, tags: [] },
  { name: "Namora", cost: 5, power: 7, tags: ["wind15"] },
  { name: "Nebula", cost: 1, power: 1, tags: [] },
  { name: "Negasonic Teenage Warhead", cost: 4, power: 5, tags: ["wind7"] },
  { name: "Nicholas Scratch", cost: 1, power: 2, tags: [] },
  { name: "Nick Fury", cost: 4, power: 6, tags: [] },
  { name: "Nico Minoru", cost: 1, power: 2, tags: ["wind1"] },
  { name: "Nightcrawler", cost: 1, power: 3, tags: ["wind4","wind6","wind7"] },
  { name: "Nightmare", cost: 3, power: 1, tags: [] },
  { name: "Nimrod", cost: 5, power: 6, tags: [] },
  { name: "Nocturne", cost: 3, power: 4, tags: ["wind6","wind7"] },
  { name: "Nova", cost: 1, power: 1, tags: ["wind14"] },
  { name: "Nova Frankie Raye", cost: 2, power: 3, tags: [] },
  { name: "Odin", cost: 6, power: 9, tags: [] },
  { name: "Okoye", cost: 2, power: 3, tags: ["wind11"] },
  { name: "Omega Red", cost: 4, power: 6, tags: [] },
  { name: "Omega Sentinel", cost: 4, power: 3, tags: [] },
  { name: "Onslaught", cost: 6, power: 8, tags: [] },
  { name: "Orka", cost: 6, power: 11, tags: ["wind5","wind6"] },
  { name: "Patriot", cost: 3, power: 2, tags: ["wind11","wind17"] },
  { name: "Peni Parker", cost: 2, power: 3, tags: [] },
  { name: "Phastos", cost: 3, power: 4, tags: [] },
  { name: "Phoenix Force", cost: 4, power: 5, tags: [] },
  { name: "Pixie", cost: 2, power: 2, tags: ["wind4","wind8"] },
  { name: "Polaris", cost: 3, power: 5, tags: ["wind5"] },
  { name: "Prodigy", cost: 3, power: 4, tags: [] },
  { name: "Professor X", cost: 5, power: 2, tags: [] },
  { name: "Prowler", cost: 3, power: 4, tags: [] },
  { name: "Proxima Midnight", cost: 4, power: 7, tags: [] },
  { name: "Psylocke", cost: 2, power: 2, tags: ["wind7","wind12","wind14"] },
  { name: "Punisher", cost: 3, power: 3, tags: [] },
  { name: "Quake", cost: 2, power: 3, tags: ["wind4"] },
  { name: "Quicksilver", cost: 1, power: 2, tags: [] },
  { name: "Quinjet", cost: 1, power: 1, tags: ["wind12"] },
  { name: "Ravonna Renslayer", cost: 2, power: 2, tags: [] },
  { name: "Red Guardian", cost: 3, power: 2, tags: [] },
  { name: "Red Hulk", cost: 6, power: 10, tags: [] },
  { name: "Red Shift", cost: 2, power: 3, tags: ["wind18"] },
  { name: "Red Skull", cost: 5, power: 14, tags: [] },
  { name: "Redwing", cost: 3, power: 5, tags: [] },
  { name: "Rescue", cost: 4, power: 4, tags: ["wind1","wind5"] },
  { name: "Rhino", cost: 2, power: 5, tags: ["wind3"] },
  { name: "Rocket and Groot", cost: 3, power: 3, tags: ["wind13","wind17"] },
  { name: "Rocket Raccoon", cost: 1, power: 1, tags: ["wind2","wind6"] },
  { name: "Rockslide", cost: 4, power: 5, tags: ["wind1","wind3"] },
  { name: "Rogue", cost: 3, power: 3, tags: [] },
  { name: "Ronan the Accuser", cost: 5, power: 5, tags: ["wind4","wind16","wind17"] },
  { name: "Sabretooth", cost: 3, power: 5, tags: ["wind7"] },
  { name: "Sage", cost: 3, power: 0, tags: ["wind6","wind8"] },
  { name: "Sam Wilson Captain America", cost: 2, power: 3, tags: ["wind19"] },
  { name: "Sandman", cost: 5, power: 8, tags: [] },
  { name: "Sandstorm", cost: 2, power: 0, tags: [] },
  { name: "Sasquatch", cost: 6, power: 10, tags: ["wind2","wind7","wind14"] },
  { name: "Sauron", cost: 1, power: 2, tags: [] },
  { name: "Scarlet Spider", cost: 4, power: 5, tags: ["wind16"] },
  { name: "Scarlet Witch", cost: 2, power: 3, tags: [] },
  { name: "Scorn", cost: 1, power: 2, tags: ["wind16"] },
  { name: "Scorpion", cost: 2, power: 3, tags: [] },
  { name: "Scream", cost: 2, power: 1, tags: ["wind10"] },
  { name: "Sebastian Shaw", cost: 3, power: 5, tags: ["wind8","wind16"] },
  { name: "Selene", cost: 1, power: 2, tags: ["wind13"] },
  { name: "Sentinel", cost: 2, power: 3, tags: [] },
  { name: "Sentry", cost: 4, power: 9, tags: [] },
  { name: "Sera", cost: 5, power: 5, tags: ["wind5"] },
  { name: "Sersi", cost: 5, power: 7, tags: ["wind8"] },
  { name: "Shadow King", cost: 3, power: 4, tags: [] },
  { name: "Shang-Chi", cost: 4, power: 3, tags: [] },
  { name: "Shang-Chi, Master of the Rings", cost: 3, power: 5, tags: [] },
  { name: "Shanna", cost: 3, power: 4, tags: [] },
  { name: "She-Hulk", cost: 6, power: 10, tags: [] },
  { name: "Shocker", cost: 2, power: 4, tags: [] },
  { name: "Shou-Lao the Undying", cost: 5, power: 6, tags: [] },
  { name: "Shuri", cost: 4, power: 3, tags: ["wind2","wind14"] },
  { name: "Silk", cost: 2, power: 5, tags: ["wind12"] },
  { name: "Silver Sable", cost: 1, power: 0, tags: [] },
  { name: "Silver Samurai", cost: 4, power: 5, tags: [] },
  { name: "Silver Surfer", cost: 3, power: 2, tags: [] },
  { name: "Silver Surfer First Steps", cost: 3, power: 5, tags: [] },
  { name: "Skaar", cost: 7, power: 12, tags: [] },
  { name: "Snowguard", cost: 1, power: 2, tags: [] },
  { name: "Sparky", cost: 2, power: 2, tags: [] },
  { name: "Spectrum", cost: 6, power: 7, tags: [] },
  { name: "Speed", cost: 3, power: 3, tags: ["wind19"] },
  { name: "Spider-Ham", cost: 1, power: 1, tags: [] },
  { name: "Spider-Man", cost: 2, power: 4, tags: ["wind2","wind8","avengers"] },
  { name: "Spider-Man 2099", cost: 5, power: 9, tags: ["wind3","wind11"] },
  { name: "Spider-Man Noir", cost: 4, power: 4, tags: [] },
  { name: "Spider-Punk", cost: 3, power: 3, tags: [] },
  { name: "Spider-Woman", cost: 5, power: 8, tags: [] },
  { name: "Squirrel Girl", cost: 1, power: 2, tags: ["wind17"] },
  { name: "Star-Lord", cost: 2, power: 2, tags: [] },
  { name: "Star-Lord, Master of the Sun", cost: 4, power: 3, tags: [] },
  { name: "Starbrand", cost: 3, power: 10, tags: [] },
  { name: "Stardust", cost: 4, power: 6, tags: [] },
  { name: "Starhawk", cost: 2, power: 2, tags: [] },
  { name: "Stature", cost: 5, power: 7, tags: ["wind9"] },
  { name: "Stegron", cost: 4, power: 7, tags: [] },
  { name: "Storm", cost: 3, power: 1, tags: ["wind10"] },
  { name: "Strange Supreme", cost: 2, power: 1, tags: [] },
  { name: "Strong Guy", cost: 3, power: 3, tags: [] },
  { name: "Sunspot", cost: 1, power: 0, tags: [] },
  { name: "Super-Adaptoid", cost: 3, power: 5, tags: [] },
  { name: "Super-Skrull", cost: 4, power: 2, tags: ["wind4"] },
  { name: "Supergiant", cost: 4, power: 6, tags: [] },
  { name: "Superior Spider-Man", cost: 3, power: 4, tags: ["wind19"] },
  { name: "Surge", cost: 2, power: 1, tags: [] },
  { name: "Surtur", cost: 3, power: 5, tags: ["wind14","wind17"] },
  { name: "Swarm", cost: 2, power: 3, tags: ["wind9"] },
  { name: "Sword Master", cost: 3, power: 7, tags: ["wind13"] },
  { name: "Symbiote Spider-Man", cost: 4, power: 7, tags: ["wind14"] },
  { name: "Taskmaster", cost: 6, power: 0, tags: [] },
  { name: "Terrax the Tamer", cost: 3, power: 4, tags: [] },
  { name: "Thaddeus Ross", cost: 2, power: 2, tags: [] },
  { name: "Thanos", cost: 6, power: 12, tags: [] },
  { name: "The Ancient One", cost: 3, power: 5, tags: [] },
  { name: "The Collector", cost: 2, power: 2, tags: [] },
  { name: "The Fallen One", cost: 5, power: 5, tags: [] },
  { name: "The First Ghost Rider", cost: 2, power: 7, tags: [] },
  { name: "The Hood", cost: 1, power: -3, tags: [] },
  { name: "The Hunger", cost: 1, power: 0, tags: [] },
  { name: "The Infinaut", cost: 6, power: 20, tags: ["wind2"] },
  { name: "The Living Tribunal", cost: 6, power: 9, tags: [] },
  { name: "The Thing", cost: 4, power: 7, tags: [] },
  { name: "The Thing First Steps", cost: 5, power: 6, tags: [] },
  { name: "Thena", cost: 2, power: 0, tags: ["wind6"] },
  { name: "Thor", cost: 3, power: 5, tags: ["wind13","wind19","avengers"] },
  { name: "Titania", cost: 1, power: 5, tags: ["wind2","wind15"] },
  { name: "Topaz", cost: 2, power: 3, tags: [] },
  { name: "Toxie Doxie", cost: 2, power: 3, tags: ["wind18"] },
  { name: "Toxin", cost: 2, power: 2, tags: [] },
  { name: "Typhoid Mary", cost: 4, power: 10, tags: ["wind6","wind13","wind14","wind15"] },
  { name: "U.S. Agent", cost: 2, power: 3, tags: ["wind3","wind6","wind9"] },
  { name: "Uatu the Watcher", cost: 1, power: 2, tags: [] },
  { name: "Ultron", cost: 6, power: 8, tags: ["wind1","wind12","wind14"] },
  { name: "Uncle Ben", cost: 1, power: 2, tags: [] },
  { name: "Valentina", cost: 2, power: 3, tags: [] },
  { name: "Valkyrie", cost: 5, power: 3, tags: [] },
  { name: "Venom", cost: 3, power: 3, tags: ["wind12"] },
  { name: "Victoria Hand", cost: 2, power: 2, tags: ["wind15"] },
  { name: "Viper", cost: 3, power: 4, tags: [] },
  { name: "Vision", cost: 5, power: 9, tags: [] },
  { name: "Viv Vision", cost: 3, power: 3, tags: [] },
  { name: "Vulture", cost: 1, power: 3, tags: [] },
  { name: "Wade Wilson", cost: 2, power: 2, tags: [] },
  { name: "War Machine", cost: 5, power: 9, tags: ["avengers"] },
  { name: "Warlock", cost: 3, power: 4, tags: [] },
  { name: "Warpath", cost: 4, power: 5, tags: [] },
  { name: "Wasp", cost: 0, power: 1, tags: [] },
  { name: "Wave", cost: 3, power: 6, tags: ["wind16"] },
  { name: "Weapon H", cost: 7, power: 14, tags: [] },
  { name: "Weapon X Wolverine", cost: 2, power: 2, tags: [] },
  { name: "Web Sling", cost: 1, power: 0, tags: ["wind19"] },
  { name: "Werewolf By Night", cost: 3, power: 3, tags: [] },
  { name: "White Queen", cost: 3, power: 5, tags: [] },
  { name: "White Tiger", cost: 5, power: 1, tags: ["wind1"] },
  { name: "White Widow", cost: 2, power: 2, tags: [] },
  { name: "Wiccan", cost: 4, power: 6, tags: [] },
  { name: "Wild Child", cost: 2, power: 1, tags: [] },
  { name: "Wolfsbane", cost: 3, power: 1, tags: ["wind1"] },
  { name: "Wolverine", cost: 2, power: 3, tags: ["wind10"] },
  { name: "Wong", cost: 4, power: 2, tags: [] },
  { name: "X-23", cost: 1, power: 1, tags: ["wind12"] },
  { name: "Xorn", cost: 2, power: 3, tags: [] },
  { name: "Yellowjacket", cost: 0, power: 2, tags: [] },
  { name: "Yondu", cost: 1, power: 2, tags: ["wind11"] },
  { name: "Zabu", cost: 1, power: 1, tags: [] },
  { name: "Zero", cost: 1, power: 3, tags: ["wind2","wind15"] },
  { name: "Zombie Captain Marvel", cost: 4, power: 4, tags: [] },
  { name: "Zombie Galacti", cost: 7, power: 5, tags: ["wind18"] },
  { name: "Zombie Giant-Man", cost: 5, power: 4, tags: [] },
  { name: "Zombie Mister Fantastic", cost: 2, power: 2, tags: ["wind19"] },
  { name: "Zombie Power Man", cost: 2, power: 4, tags: [] },
  { name: "Zombie Scarlet Witch", cost: 3, power: 4, tags: [] },
  { name: "Zombie Sentry", cost: 3, power: 4, tags: [] }
];

const cards = cardDatabase.map(c => c.name);
